# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Typed RPC contracts for the house demonstration sequence."""

from typing import Any, Protocol

from dimos.imitation.policy.module import PolicyControlSpec, RolloutStatus
from dimos.imitation.policy.skills import PolicyRolloutSpec
from dimos.spec.utils import Spec


class PackingPolicySpec(PolicyRolloutSpec, Protocol):
    def clear_rollout_observations(self) -> RolloutStatus: ...


class HomeControlSpec(PolicyControlSpec, Protocol):
    def get_joint_positions(self) -> dict[str, float]: ...
    def task_invoke(
        self, task_name: str, method: str, kwargs: dict[str, Any] | None = None
    ) -> Any: ...


class HomeSimSpec(Spec, Protocol):
    def is_simulation_running(self) -> bool: ...
    def packing_order(self, seed: int | None = None) -> list[int]: ...
    def packing_state(self) -> dict[str, Any]: ...
    def select_bottle(self, index: int) -> dict[str, Any]: ...
    def task_state(self) -> dict[str, Any]: ...
    def navigation_status(self) -> dict[str, Any]: ...
    def plan_departure(self, yaw: float) -> list[list[float]]: ...
    def publish_navigation_map(self, cloud_path: str) -> None: ...
    def request_navigation_path(self, target: list[float]) -> None: ...
    def stop_navigation_base(self) -> None: ...
    def validate_navigation_path(self, path: list[list[float]]) -> None: ...
    def plan_transport(self, x: float, y: float, yaw: float | None = None) -> list[list[float]]: ...
    def plan_tray_motion(
        self, phase: str, target: list[float] | None = None
    ) -> list[dict[str, Any]]: ...
    def prepare_tray_holding(self) -> None: ...
    def set_tray_delivery_view(self) -> None: ...
    def simulation_snapshot(self) -> dict[str, Any]: ...
    def tray_destination(self) -> dict[str, Any]: ...


class HomeSceneSpec(HomeSimSpec, Protocol):
    def prepare_home_scene(self) -> dict[str, Any]: ...
    def home_session(self) -> dict[str, Any]: ...
