package com.dimensional.mini4pro.record

import java.io.Closeable
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStreamWriter
import java.io.Writer

/**
 * Where the recorder's lines go. One interface so the whole writer can be driven
 * by an in-memory sink in a JVM unit test — including rotation and the
 * flush/durability policy, which are the parts most likely to be wrong and least
 * likely to be exercised on a phone before a flight.
 */
interface LogSink : Closeable {
    /** Human-readable name of this part, recorded in the header. */
    val name: String

    /** Bytes handed to this sink so far. Drives rotation. */
    val bytesWritten: Long

    fun writeLine(line: String)

    /**
     * [durable] `false` pushes bytes out of our buffer into the kernel — enough to
     * survive a process crash. `true` additionally asks the kernel to put them on
     * the flash, which is what survives a battery pull or a phone reboot. The
     * difference is roughly a millisecond versus tens of milliseconds, which is
     * why the two are separate and the policy is in [RecorderConfig].
     */
    fun flush(durable: Boolean)
}

/** Opens sink parts and enforces the disk budget. */
interface SinkFactory {
    /** Opens part [part] (1-based) of session [session]. */
    fun open(session: String, part: Int): LogSink

    /**
     * Deletes the oldest parts of [session] beyond [keep].
     *
     * Dropping the **oldest** is the right way round: a fault is diagnosed from
     * the seconds before it, so the tail is what must survive an unbounded flight.
     */
    fun prune(session: String, keep: Int): Int
}

/**
 * A JSONL file. Buffered by an explicit 64 kB writer rather than left to the
 * default, so the amount of data at risk between flushes is a number we can state
 * rather than a library detail.
 */
class FileLogSink(private val file: File) : LogSink {
    private val stream = FileOutputStream(file, true)
    private val writer: Writer = OutputStreamWriter(stream, Charsets.UTF_8).buffered(BUFFER_BYTES)

    override val name: String get() = file.name

    override var bytesWritten: Long = file.length()
        private set

    override fun writeLine(line: String) {
        writer.write(line)
        writer.write("\n")
        // Counted from the string rather than the file so rotation does not need a
        // stat() per line. ASCII-only in practice (hex, enum names, our own
        // messages); a multi-byte character would undercount slightly, which only
        // makes files marginally larger than the budget.
        bytesWritten += line.length + 1
    }

    override fun flush(durable: Boolean) {
        writer.flush()
        if (durable) {
            stream.flush()
            stream.fd.sync()
        }
    }

    override fun close() {
        try {
            flush(durable = true)
        } finally {
            writer.close()
        }
    }

    companion object {
        const val BUFFER_BYTES = 64 * 1024
    }
}

/**
 * Session files in one directory, named `<session>.NNN.jsonl`.
 *
 * The session id is generated by the caller from wall-clock time so files sort
 * chronologically in `adb shell ls` and in the phone's file manager, which is how
 * they will actually be found.
 */
class FileSinkFactory(private val dir: File) : SinkFactory {

    override fun open(session: String, part: Int): LogSink {
        dir.mkdirs()
        return FileLogSink(File(dir, fileName(session, part)))
    }

    override fun prune(session: String, keep: Int): Int {
        val parts = dir.listFiles { f -> f.name.startsWith("$session.") && f.name.endsWith(SUFFIX) }
            ?.sortedBy { it.name }
            ?: return 0
        if (parts.size <= keep) return 0
        var removed = 0
        for (f in parts.take(parts.size - keep)) {
            if (f.delete()) removed++
        }
        return removed
    }

    /** Removes whole sessions beyond the newest [keepSessions]. */
    fun pruneSessions(keepSessions: Int): Int {
        val sessions = dir.listFiles { f -> f.name.endsWith(SUFFIX) }
            ?.mapNotNull { it.name.substringBefore('.').takeIf { s -> s.isNotEmpty() } }
            ?.distinct()
            ?.sorted()
            ?: return 0
        if (sessions.size <= keepSessions) return 0
        var removed = 0
        for (s in sessions.take(sessions.size - keepSessions)) {
            removed += prune(s, 0)
        }
        return removed
    }

    companion object {
        const val SUFFIX = ".jsonl"
        fun fileName(session: String, part: Int) = "%s.%03d%s".format(session, part, SUFFIX)
    }
}
