CREATE TABLE "agents" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"tagline" text NOT NULL,
	"description" text NOT NULL,
	"avatar_key" text,
	"emoji" text,
	"services" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"base_price_usd" double precision DEFAULT 0 NOT NULL,
	"is_real" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'coming_soon' NOT NULL,
	"chain" text DEFAULT 'eip155:11155111' NOT NULL,
	"agent_id" text,
	"agent_wallet" text,
	"register_tx" text,
	"capabilities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "agents_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"agent_slug" text NOT NULL,
	"requester_addr" text,
	"requester_user_id" text,
	"service" text NOT NULL,
	"status" text DEFAULT 'booked' NOT NULL,
	"price_usd" double precision DEFAULT 0 NOT NULL,
	"paid" boolean DEFAULT false NOT NULL,
	"payment_mode" text DEFAULT 'mock' NOT NULL,
	"payment_tx" text,
	"command" text,
	"run" text,
	"splat_id" text,
	"rating" integer,
	"feedback_tx" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"dispatched_at" timestamp,
	"completed_at" timestamp
);
