# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from importlib import import_module
from pathlib import Path


def schema_root():
    return Path(__file__).with_name("schemas")


def package_root():
    return Path(__file__).with_name("package")


def message_types():
    values = import_module("dimos_generated")
    names = [
        "builtin_interfaces/msg/Duration",
        "builtin_interfaces/msg/Time",
        "std_msgs/msg/Header",
        "vision_msgs/msg/Point2D",
        "vision_msgs/msg/Pose2D",
        "vision_msgs/msg/BoundingBox2D",
        "dimos_msgs/msg/BoundingBox2DArray",
        "geometry_msgs/msg/Point",
        "geometry_msgs/msg/Quaternion",
        "geometry_msgs/msg/Pose",
        "geometry_msgs/msg/Vector3",
        "vision_msgs/msg/BoundingBox3D",
        "dimos_msgs/msg/BoundingBox3DArray",
        "dimos_msgs/msg/Contact",
        "dimos_msgs/msg/Contacts",
        "dimos_msgs/msg/EntityMarker",
        "dimos_msgs/msg/EntityMarkers",
        "dimos_msgs/msg/GraspCandidate",
        "dimos_msgs/msg/GraspCandidateArray",
        "dimos_msgs/msg/ImuInfo",
        "dimos_msgs/msg/JointCommand",
        "dimos_msgs/msg/LineSegment3D",
        "dimos_msgs/msg/LineSegments3D",
        "dimos_msgs/msg/MotorCommandArray",
        "dimos_msgs/msg/RegionBounds",
        "dimos_msgs/msg/RegionLineSegments3D",
        "sensor_msgs/msg/PointField",
        "sensor_msgs/msg/PointCloud2",
        "dimos_msgs/msg/RegionPointCloud2",
        "dimos_msgs/msg/RobotState",
        "dimos_msgs/msg/TrajectoryStatus",
        "dimos_msgs/msg/VideoStats",
        "foxglove_msgs/msg/CompressedVideo",
        "geometry_msgs/msg/Accel",
        "geometry_msgs/msg/AccelStamped",
        "geometry_msgs/msg/AccelWithCovariance",
        "geometry_msgs/msg/AccelWithCovarianceStamped",
        "geometry_msgs/msg/Inertia",
        "geometry_msgs/msg/InertiaStamped",
        "geometry_msgs/msg/Point32",
        "geometry_msgs/msg/PointStamped",
        "geometry_msgs/msg/Polygon",
        "geometry_msgs/msg/PolygonInstance",
        "geometry_msgs/msg/PolygonInstanceStamped",
        "geometry_msgs/msg/PolygonStamped",
        "geometry_msgs/msg/Pose2D",
        "geometry_msgs/msg/PoseArray",
        "geometry_msgs/msg/PoseStamped",
        "geometry_msgs/msg/PoseWithCovariance",
        "geometry_msgs/msg/PoseWithCovarianceStamped",
        "geometry_msgs/msg/QuaternionStamped",
        "geometry_msgs/msg/Transform",
        "geometry_msgs/msg/TransformStamped",
        "geometry_msgs/msg/Twist",
        "geometry_msgs/msg/TwistStamped",
        "geometry_msgs/msg/TwistWithCovariance",
        "geometry_msgs/msg/TwistWithCovarianceStamped",
        "geometry_msgs/msg/Vector3Stamped",
        "geometry_msgs/msg/VelocityStamped",
        "geometry_msgs/msg/VelocityWithCovarianceStamped",
        "geometry_msgs/msg/Wrench",
        "geometry_msgs/msg/WrenchStamped",
        "nav_msgs/msg/Goals",
        "nav_msgs/msg/GridCells",
        "nav_msgs/msg/MapMetaData",
        "nav_msgs/msg/OccupancyGrid",
        "nav_msgs/msg/Odometry",
        "nav_msgs/msg/Path",
        "nav_msgs/msg/TrajectoryPoint",
        "nav_msgs/msg/Trajectory",
        "sensor_msgs/msg/BatteryState",
        "sensor_msgs/msg/RegionOfInterest",
        "sensor_msgs/msg/CameraInfo",
        "sensor_msgs/msg/ChannelFloat32",
        "sensor_msgs/msg/CompressedImage",
        "sensor_msgs/msg/FluidPressure",
        "sensor_msgs/msg/Illuminance",
        "sensor_msgs/msg/Image",
        "sensor_msgs/msg/Imu",
        "sensor_msgs/msg/JointState",
        "sensor_msgs/msg/Joy",
        "sensor_msgs/msg/JoyFeedback",
        "sensor_msgs/msg/JoyFeedbackArray",
        "sensor_msgs/msg/LaserEcho",
        "sensor_msgs/msg/LaserScan",
        "sensor_msgs/msg/MagneticField",
        "sensor_msgs/msg/MultiDOFJointState",
        "sensor_msgs/msg/MultiEchoLaserScan",
        "sensor_msgs/msg/NavSatStatus",
        "sensor_msgs/msg/NavSatFix",
        "sensor_msgs/msg/PointCloud",
        "sensor_msgs/msg/Range",
        "sensor_msgs/msg/RelativeHumidity",
        "sensor_msgs/msg/Temperature",
        "sensor_msgs/msg/TimeReference",
        "shape_msgs/msg/MeshTriangle",
        "shape_msgs/msg/Mesh",
        "shape_msgs/msg/Plane",
        "shape_msgs/msg/SolidPrimitive",
        "std_msgs/msg/Bool",
        "std_msgs/msg/Byte",
        "std_msgs/msg/MultiArrayDimension",
        "std_msgs/msg/MultiArrayLayout",
        "std_msgs/msg/ByteMultiArray",
        "std_msgs/msg/Char",
        "std_msgs/msg/ColorRGBA",
        "std_msgs/msg/Empty",
        "std_msgs/msg/Float32",
        "std_msgs/msg/Float32MultiArray",
        "std_msgs/msg/Float64",
        "std_msgs/msg/Float64MultiArray",
        "std_msgs/msg/Int16",
        "std_msgs/msg/Int16MultiArray",
        "std_msgs/msg/Int32",
        "std_msgs/msg/Int32MultiArray",
        "std_msgs/msg/Int64",
        "std_msgs/msg/Int64MultiArray",
        "std_msgs/msg/Int8",
        "std_msgs/msg/Int8MultiArray",
        "std_msgs/msg/String",
        "std_msgs/msg/UInt16",
        "std_msgs/msg/UInt16MultiArray",
        "std_msgs/msg/UInt32",
        "std_msgs/msg/UInt32MultiArray",
        "std_msgs/msg/UInt64",
        "std_msgs/msg/UInt64MultiArray",
        "std_msgs/msg/UInt8",
        "std_msgs/msg/UInt8MultiArray",
        "tf2_msgs/msg/TF2Error",
        "tf2_msgs/msg/TFMessage",
        "trajectory_msgs/msg/JointTrajectoryPoint",
        "trajectory_msgs/msg/JointTrajectory",
        "trajectory_msgs/msg/MultiDOFJointTrajectoryPoint",
        "trajectory_msgs/msg/MultiDOFJointTrajectory",
        "vision_msgs/msg/BoundingBox2DArray",
        "vision_msgs/msg/BoundingBox3DArray",
        "vision_msgs/msg/ObjectHypothesis",
        "vision_msgs/msg/Classification",
        "vision_msgs/msg/ObjectHypothesisWithPose",
        "vision_msgs/msg/Detection2D",
        "vision_msgs/msg/Detection2DArray",
        "vision_msgs/msg/Detection3D",
        "vision_msgs/msg/Detection3DArray",
        "vision_msgs/msg/VisionClass",
        "vision_msgs/msg/LabelInfo",
        "vision_msgs/msg/VisionInfo",
        "visualization_msgs/msg/ImageMarker",
        "visualization_msgs/msg/MeshFile",
        "visualization_msgs/msg/UVCoordinate",
        "visualization_msgs/msg/Marker",
        "visualization_msgs/msg/InteractiveMarkerControl",
        "visualization_msgs/msg/MenuEntry",
        "visualization_msgs/msg/InteractiveMarker",
        "visualization_msgs/msg/InteractiveMarkerFeedback",
        "visualization_msgs/msg/InteractiveMarkerInit",
        "visualization_msgs/msg/InteractiveMarkerPose",
        "visualization_msgs/msg/InteractiveMarkerUpdate",
        "visualization_msgs/msg/MarkerArray",
    ]
    return {
        name: getattr(getattr(values, name.split("/")[0]).msg, name.split("/")[-1])
        for name in names
    }
