# Copyright 2025-2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for AprilTagDetector.

Uses synthetic marker images generated by OpenCV so the test suite does not
depend on external fixtures or hardware recordings.
"""

from __future__ import annotations

import math

import cv2
import numpy as np
import pytest

from dimos.msgs.sensor_msgs.CameraInfo import CameraInfo
from dimos.msgs.sensor_msgs.Image import Image
from dimos.perception.detection.detectors.apriltag import AprilTagDetector


_TEST_FX = 500.0
_TEST_FY = 500.0
_TEST_CX = 320.0
_TEST_CY = 240.0


def _make_test_camera_info(width: int = 640, height: int = 480) -> CameraInfo:
    """Build a simple pinhole CameraInfo for testing."""
    return CameraInfo(
        width=width,
        height=height,
        K=[_TEST_FX, 0.0, _TEST_CX, 0.0, _TEST_FY, _TEST_CY, 0.0, 0.0, 1.0],
        D=[0.0, 0.0, 0.0, 0.0, 0.0],
        frame_id="camera_optical",
    )


def _synthetic_tag_image(
    tag_id: int = 42,
    family: str = "tag36h11",
    tag_size_m: float = 0.165,
    depth_m: float = 1.0,
    width: int = 640,
    height: int = 480,
    tag_shift_px: tuple[int, int] = (0, 0),
) -> Image:
    """Render a synthetic marker image with the tag centred at (cx, cy)+shift.

    The tag is rendered face-on to the camera (camera Z perpendicular to tag
    plane) so the translation from solvePnP should be approximately
    (shift_x/width, shift_y/height, depth_m) and the rotation should be close
    to identity.
    """
    # Determine apparent tag size in pixels from intrinsics + depth.
    apparent_size_px = int(_TEST_FX * tag_size_m / depth_m)
    if apparent_size_px < 20:
        # Too small for reliable detection at test resolution.
        apparent_size_px = max(20, apparent_size_px)

    aruco_dict = cv2.aruco.getPredefinedDictionary(
        {
            "tag36h11": cv2.aruco.DICT_APRILTAG_36h11,
            "tag25h9": cv2.aruco.DICT_APRILTAG_25h9,
            "tag16h5": cv2.aruco.DICT_APRILTAG_16h5,
            "aruco_4x4_50": cv2.aruco.DICT_4X4_50,
        }[family]
    )
    marker_img = cv2.aruco.generateImageMarker(aruco_dict, tag_id, apparent_size_px)

    canvas = np.full((height, width), 255, dtype=np.uint8)
    cx = width // 2 + tag_shift_px[0]
    cy = height // 2 + tag_shift_px[1]
    half = apparent_size_px // 2
    y0 = max(0, cy - half)
    y1 = min(height, cy + half)
    x0 = max(0, cx - half)
    x1 = min(width, cx + half)
    # Paste marker (account for border in case of clipping).
    mh = y1 - y0
    mw = x1 - x0
    canvas[y0:y1, x0:x1] = marker_img[:mh, :mw]

    # Convert to BGR for dimos Image (to_opencv expects BGR).
    color = cv2.cvtColor(canvas, cv2.COLOR_GRAY2BGR)
    img = Image.from_opencv(color)
    img.frame_id = "camera_optical"
    img.ts = 0.0
    return img


class TestAprilTagDetector:
    @pytest.fixture(scope="class")
    def detector(self) -> AprilTagDetector:
        return AprilTagDetector(family="tag36h11", tag_size_m=0.165)

    @pytest.fixture(scope="class")
    def camera_info(self) -> CameraInfo:
        return _make_test_camera_info()

    def test_detect_known_tag(self, detector: AprilTagDetector, camera_info: CameraInfo) -> None:
        """A single face-on marker at 1 m should be detected once with correct ID."""
        img = _synthetic_tag_image(tag_id=42, depth_m=1.0)
        results = detector.detect(img, camera_info)
        assert len(results) == 1
        assert results[0].tag_id == 42
        assert results[0].family == "tag36h11"
        assert results[0].corner_count == 4

    def test_pose_depth_is_approximate(self, detector: AprilTagDetector, camera_info: CameraInfo) -> None:
        """The Z translation should be within 10 % of the synthetic depth."""
        expected_depth = 1.0
        img = _synthetic_tag_image(tag_id=7, depth_m=expected_depth)
        results = detector.detect(img, camera_info)
        assert len(results) == 1
        det = results[0]
        z = det.pose.position.z
        assert abs(z - expected_depth) < 0.1 * expected_depth, f"Z={z}, expected {expected_depth}"

    def test_pose_orientation_identity(self, detector: AprilTagDetector, camera_info: CameraInfo) -> None:
        """A face-on tag should have rotation close to identity."""
        img = _synthetic_tag_image(tag_id=3, depth_m=1.0)
        results = detector.detect(img, camera_info)
        assert len(results) == 1
        q = results[0].pose.orientation
        # Quaternion identity is (0, 0, 0, 1).  Allow small numerical noise.
        assert abs(q.w - 1.0) < 0.05
        assert abs(q.x) < 0.05
        assert abs(q.y) < 0.05

    def test_empty_image(self, detector: AprilTagDetector, camera_info: CameraInfo) -> None:
        """Blank image should yield no detections."""
        blank = np.full((480, 640, 3), 128, dtype=np.uint8)
        img = Image.from_opencv(blank)
        results = detector.detect(img, camera_info)
        assert len(results) == 0

    def test_multiple_tags(self, detector: AprilTagDetector, camera_info: CameraInfo) -> None:
        """Canvas with two distinct markers should return two detections."""
        # Render two separate synthetic images, shift one, merge into a single canvas.
        img1 = _synthetic_tag_image(tag_id=10, depth_m=1.0, tag_shift_px=(-80, -60))
        img2 = _synthetic_tag_image(tag_id=20, depth_m=1.0, tag_shift_px=(80, 60))
        canvas = np.full((480, 640, 3), 255, dtype=np.uint8)
        # Paste the greyscale render of each (they have black borders on white bg).
        grey1 = cv2.cvtColor(img1.to_opencv(), cv2.COLOR_BGR2GRAY)
        grey2 = cv2.cvtColor(img2.to_opencv(), cv2.COLOR_BGR2GRAY)
        mask1 = grey1 < 200
        mask2 = grey2 < 200
        canvas[mask1] = [0, 0, 0]
        canvas[mask2] = [0, 0, 0]
        merged = Image.from_opencv(canvas)
        results = detector.detect(merged, camera_info)
        ids = {r.tag_id for r in results}
        assert ids == {10, 20}

    def test_wrong_family_returns_nothing(self, detector: AprilTagDetector, camera_info: CameraInfo) -> None:
        """A tag36h11 detector should not detect an aruco_4x4 marker."""
        # Generate aruco_4x4_50 marker with the aruco family.
        aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
        marker = cv2.aruco.generateImageMarker(aruco_dict, 5, 100)
        canvas = np.full((480, 640), 255, dtype=np.uint8)
        canvas[190:290, 270:370] = marker
        color = cv2.cvtColor(canvas, cv2.COLOR_GRAY2BGR)
        img = Image.from_opencv(color)
        results = detector.detect(img, camera_info)
        assert len(results) == 0

    def test_invalid_family_raises(self) -> None:
        with pytest.raises(ValueError, match="Unknown AprilTag family"):
            AprilTagDetector(family="not_a_family", tag_size_m=0.1)

    def test_negative_tag_size_raises(self) -> None:
        with pytest.raises(ValueError, match="tag_size_m must be"):
            AprilTagDetector(family="tag36h11", tag_size_m=-0.1)


class TestAprilTagDetectorPoseConsistency:
    """Regression tests against synthetic known geometry."""

    @pytest.fixture(scope="class")
    def detector_small(self) -> AprilTagDetector:
        # Smaller tag for closer-depth testing.
        return AprilTagDetector(family="tag36h11", tag_size_m=0.08)

    @pytest.fixture(scope="class")
    def camera_info(self) -> CameraInfo:
        return _make_test_camera_info()

    @pytest.mark.parametrize("depth", [0.5, 1.0, 2.0, 3.0])
    def test_depth_scale(self, detector_small: AprilTagDetector, camera_info: CameraInfo, depth: float) -> None:
        """Estimated Z should scale approximately linearly with true depth."""
        img = _synthetic_tag_image(
            tag_id=99,
            tag_size_m=0.08,
            depth_m=depth,
            tag_shift_px=(0, 0),
        )
        results = detector_small.detect(img, camera_info)
        assert len(results) == 1
        z = results[0].pose.position.z
        # Tolerate 15 % error due to synthetic / ideal nature.
        assert abs(z - depth) < 0.15 * depth, f"depth {depth} got Z={z}"
