---
services:
  dimos-model-semantic-seg:
    image: dimos-model-semantic-seg:latest
    build: 
      context: ../../../
      dockerfile: docker/models/semantic_seg/Dockerfile
    env_file:
      - ../../../.env
    mem_limit: 8048m
    volumes:
      - ../../../assets:/app/assets
    ports:
      - "5555:5555"
    runtime: nvidia
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: [ "python", "-m", "tests.test_semantic_seg_video_agent" ]
    stdin_open: true
    tty: true

# IMPORTANT: This runs soley on the NVIDA GPU

# ----
# TO RUN:
#   docker build -f ./Dockerfile -t dimos-models ../../ && docker compose up
# GO TO:
#   127.0.0.1:5555 (when flask server fixed)
# ----
