package com.dimensional.mini4pro.zenoh

/**
 * One codec per LCM type, both directions.
 *
 * The types are those in `docs/zenoh-topics.md` and everything they nest. Each
 * codec knows three things: its package-qualified name (which is part of the
 * Zenoh key — `<prefix>/<channel>/<pkg>.<Type>`), its pinned fingerprint, and how
 * to move its fields.
 *
 * ## Nested versus top-level
 *
 * [encodeInto] and [decodeFrom] handle the **body only**: nested LCM structs are
 * inlined with no fingerprint of their own. [encode] and [decode] are the
 * top-level pair, and they are the only place the 8-byte prefix is written or
 * checked. Composing a codec inside another therefore always uses the `Into`/
 * `From` pair — the fingerprint appears exactly once, at the front of a payload.
 *
 * ## Field order is the wire order, and it is not always the ROS order
 *
 * Several types put a field first that no reader expects there, because lcm-gen
 * hoists variable-array length fields to the front of the struct:
 *
 * - [PathCodec] writes `poses_length` **before** `header`.
 * - [BatteryStateCodec] writes `cell_voltage_length` and
 *   `cell_temperature_length` **before** `header`.
 * - [CameraInfoCodec] writes `D_length` **before** `header`, and `height`
 *   before `width`.
 * - [Detection3DCodec] writes `results_length` **before** `header`, and is the
 *   only one with fields *after* its array.
 * - [Detection3DArrayCodec] writes `detections_length` **before** `header`, and
 *   carries a [Detection3DCodec] inside each element — two hoisted lengths on
 *   one wire, nested.
 *
 * Every one is confirmed byte-for-byte against fixtures generated by DiMOS's own
 * Python (`android/app/src/test/resources/lcm/`, from `tools/lcmfixtures/`).
 */
interface LcmCodec<T> {
    /** Package-qualified, exactly as it appears in a Zenoh key: `nav_msgs.Odometry`. */
    val typeName: String

    /** The pinned 8-byte fingerprint from [LcmFingerprints]. */
    val fingerprint: Long

    /** Writes the body — no fingerprint. This is what nesting uses. */
    fun encodeInto(w: LcmWriter, value: T)

    /** Reads the body — no fingerprint. This is what nesting uses. */
    fun decodeFrom(r: LcmReader): T

    /** A complete payload: fingerprint then body. What goes on the wire. */
    fun encode(value: T): ByteArray {
        val w = LcmWriter()
        w.writeFingerprint(fingerprint)
        encodeInto(w, value)
        return w.toByteArray()
    }

    /**
     * A complete payload, checked. Throws [LcmDecodeException] on a wrong
     * fingerprint, a truncated body, or trailing bytes — all three mean the
     * sender is not speaking the type we think, and a partial decode of a
     * command is worse than no command.
     */
    fun decode(bytes: ByteArray): T {
        val r = LcmReader(bytes)
        r.expectFingerprint(fingerprint, typeName)
        val value = decodeFrom(r)
        if (r.remaining != 0) {
            throw LcmDecodeException("$typeName: ${r.remaining} trailing bytes after a complete message")
        }
        return value
    }
}

/** Writes a fixed-size covariance, refusing a list of the wrong length. */
private fun LcmWriter.writeCovariance(values: List<Double>, size: Int, what: String) {
    require(values.size == size) { "$what: covariance must be $size doubles, got ${values.size}" }
    for (v in values) writeDouble(v)
}

private fun LcmReader.readCovariance(size: Int): List<Double> {
    val out = ArrayList<Double>(size)
    for (i in 0 until size) out.add(readDouble())
    return out
}

// ---------------------------------------------------------------------------
// builtin_interfaces
// ---------------------------------------------------------------------------

/**
 * `builtin_interfaces.Time` — `int32 sec, int32 nanosec`.
 *
 * Byte-identical to [TimeCodec] and a different type: the second field is `nanosec` rather than
 * `nsec`, so the fingerprints differ even though nothing on the wire does. It is nested by exactly
 * one type in this catalogue, [CompressedVideoCodec], and that is the only reason it exists.
 */
object BuiltinTimeCodec : LcmCodec<LcmTime> {
    override val typeName = "builtin_interfaces.Time"
    override val fingerprint = LcmFingerprints.BUILTIN_INTERFACES_TIME

    override fun encodeInto(w: LcmWriter, value: LcmTime) {
        w.writeInt(value.sec)
        w.writeInt(value.nsec)
    }

    override fun decodeFrom(r: LcmReader) = LcmTime(r.readInt(), r.readInt())
}

// ---------------------------------------------------------------------------
// std_msgs
// ---------------------------------------------------------------------------

/** `std_msgs.Time` — `int32 sec, int32 nsec`. */
object TimeCodec : LcmCodec<LcmTime> {
    override val typeName = "std_msgs.Time"
    override val fingerprint = LcmFingerprints.STD_MSGS_TIME

    override fun encodeInto(w: LcmWriter, value: LcmTime) {
        w.writeInt(value.sec)
        w.writeInt(value.nsec)
    }

    override fun decodeFrom(r: LcmReader) = LcmTime(r.readInt(), r.readInt())
}

/** `std_msgs.Header` — `int32 seq, std_msgs.Time stamp, string frame_id`. */
object HeaderCodec : LcmCodec<LcmHeader> {
    override val typeName = "std_msgs.Header"
    override val fingerprint = LcmFingerprints.STD_MSGS_HEADER

    override fun encodeInto(w: LcmWriter, value: LcmHeader) {
        w.writeInt(value.seq)
        TimeCodec.encodeInto(w, value.stamp)
        w.writeString(value.frameId)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmHeader(r.readInt(), TimeCodec.decodeFrom(r), r.readString())
}

/**
 * `std_msgs.String` — a bare Kotlin [String], because the type has exactly one
 * field and a wrapper class would earn nothing.
 *
 * Carries `mode`, `status`, `health` and `command_ack`; the last three are JSON
 * text in `data`, which this codec neither parses nor validates.
 */
object StringCodec : LcmCodec<String> {
    override val typeName = "std_msgs.String"
    override val fingerprint = LcmFingerprints.STD_MSGS_STRING

    override fun encodeInto(w: LcmWriter, value: String) {
        w.writeString(value)
    }

    override fun decodeFrom(r: LcmReader): String = r.readString()
}

/**
 * `std_msgs.Float32` — `float data`. Twelve bytes on the wire: the fingerprint and one
 * IEEE-754 single. Carries `wind`, and the *narrowing* is not this codec's to do —
 * `ZenohTelemetryEncoder.windOrNull` owns the dm/s→m/s conversion and hands a [LcmFloat32]
 * already at single precision, so a byte comparison against DiMOS's encoder tests the
 * conversion and not just the plumbing.
 */
object Float32Codec : LcmCodec<LcmFloat32> {
    override val typeName = "std_msgs.Float32"
    override val fingerprint = LcmFingerprints.STD_MSGS_FLOAT32

    override fun encodeInto(w: LcmWriter, value: LcmFloat32) {
        w.writeFloat(value.data)
    }

    override fun decodeFrom(r: LcmReader) = LcmFloat32(r.readFloat())
}

// ---------------------------------------------------------------------------
// geometry_msgs
// ---------------------------------------------------------------------------

/** `geometry_msgs.Point` — `double x, y, z`. */
object PointCodec : LcmCodec<LcmPoint> {
    override val typeName = "geometry_msgs.Point"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_POINT

    override fun encodeInto(w: LcmWriter, value: LcmPoint) {
        w.writeDouble(value.x)
        w.writeDouble(value.y)
        w.writeDouble(value.z)
    }

    override fun decodeFrom(r: LcmReader) = LcmPoint(r.readDouble(), r.readDouble(), r.readDouble())
}

/**
 * `geometry_msgs.Vector3` — `double x, y, z`.
 *
 * Byte-identical to [PointCodec], fingerprint and all. The Zenoh key is what
 * distinguishes them, so the `gimbal` channel gets its own codec name.
 */
object Vector3Codec : LcmCodec<LcmVector3> {
    override val typeName = "geometry_msgs.Vector3"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_VECTOR3

    override fun encodeInto(w: LcmWriter, value: LcmVector3) {
        w.writeDouble(value.x)
        w.writeDouble(value.y)
        w.writeDouble(value.z)
    }

    override fun decodeFrom(r: LcmReader) = LcmVector3(r.readDouble(), r.readDouble(), r.readDouble())
}

/** `geometry_msgs.Quaternion` — `x, y, z, w`. **`w` is written last.** */
object QuaternionCodec : LcmCodec<LcmQuaternion> {
    override val typeName = "geometry_msgs.Quaternion"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_QUATERNION

    override fun encodeInto(w: LcmWriter, value: LcmQuaternion) {
        w.writeDouble(value.x)
        w.writeDouble(value.y)
        w.writeDouble(value.z)
        w.writeDouble(value.w)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmQuaternion(r.readDouble(), r.readDouble(), r.readDouble(), r.readDouble())
}

/** `geometry_msgs.Pose` — `Point position, Quaternion orientation`. */
object PoseCodec : LcmCodec<LcmPose> {
    override val typeName = "geometry_msgs.Pose"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_POSE

    override fun encodeInto(w: LcmWriter, value: LcmPose) {
        PointCodec.encodeInto(w, value.position)
        QuaternionCodec.encodeInto(w, value.orientation)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmPose(PointCodec.decodeFrom(r), QuaternionCodec.decodeFrom(r))
}

/** `geometry_msgs.PoseWithCovariance` — `Pose pose, double[36] covariance`. */
object PoseWithCovarianceCodec : LcmCodec<LcmPoseWithCovariance> {
    override val typeName = "geometry_msgs.PoseWithCovariance"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_POSE_WITH_COVARIANCE

    override fun encodeInto(w: LcmWriter, value: LcmPoseWithCovariance) {
        PoseCodec.encodeInto(w, value.pose)
        w.writeCovariance(value.covariance, COVARIANCE_SIZE_36, typeName)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmPoseWithCovariance(PoseCodec.decodeFrom(r), r.readCovariance(COVARIANCE_SIZE_36))
}

/** `geometry_msgs.Twist` — `Vector3 linear, Vector3 angular`. The `cmd_vel` channel. */
object TwistCodec : LcmCodec<LcmTwist> {
    override val typeName = "geometry_msgs.Twist"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_TWIST

    override fun encodeInto(w: LcmWriter, value: LcmTwist) {
        Vector3Codec.encodeInto(w, value.linear)
        Vector3Codec.encodeInto(w, value.angular)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmTwist(Vector3Codec.decodeFrom(r), Vector3Codec.decodeFrom(r))
}

/**
 * `geometry_msgs.TwistStamped` — `Header header, Twist twist`. The `setpoint` channel: the
 * velocity command this bridge handed the aircraft, stamped and framed.
 */
object TwistStampedCodec : LcmCodec<LcmTwistStamped> {
    override val typeName = "geometry_msgs.TwistStamped"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_TWIST_STAMPED

    override fun encodeInto(w: LcmWriter, value: LcmTwistStamped) {
        HeaderCodec.encodeInto(w, value.header)
        TwistCodec.encodeInto(w, value.twist)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmTwistStamped(HeaderCodec.decodeFrom(r), TwistCodec.decodeFrom(r))
}

/** `geometry_msgs.TwistWithCovariance` — `Twist twist, double[36] covariance`. */
object TwistWithCovarianceCodec : LcmCodec<LcmTwistWithCovariance> {
    override val typeName = "geometry_msgs.TwistWithCovariance"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_TWIST_WITH_COVARIANCE

    override fun encodeInto(w: LcmWriter, value: LcmTwistWithCovariance) {
        TwistCodec.encodeInto(w, value.twist)
        w.writeCovariance(value.covariance, COVARIANCE_SIZE_36, typeName)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmTwistWithCovariance(TwistCodec.decodeFrom(r), r.readCovariance(COVARIANCE_SIZE_36))
}

/** `geometry_msgs.PoseStamped` — the `goal` channel and each element of a `path`. */
object PoseStampedCodec : LcmCodec<LcmPoseStamped> {
    override val typeName = "geometry_msgs.PoseStamped"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_POSE_STAMPED

    override fun encodeInto(w: LcmWriter, value: LcmPoseStamped) {
        HeaderCodec.encodeInto(w, value.header)
        PoseCodec.encodeInto(w, value.pose)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmPoseStamped(HeaderCodec.decodeFrom(r), PoseCodec.decodeFrom(r))
}

/** `geometry_msgs.PointStamped` — the `roi` channel. */
object PointStampedCodec : LcmCodec<LcmPointStamped> {
    override val typeName = "geometry_msgs.PointStamped"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_POINT_STAMPED

    override fun encodeInto(w: LcmWriter, value: LcmPointStamped) {
        HeaderCodec.encodeInto(w, value.header)
        PointCodec.encodeInto(w, value.point)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmPointStamped(HeaderCodec.decodeFrom(r), PointCodec.decodeFrom(r))
}

/**
 * `geometry_msgs.Transform` — `Vector3 translation, Quaternion rotation`.
 *
 * The same bytes as a [PoseCodec] body and a different fingerprint, because lcm-gen hashes field
 * names. Composing the wrong one produces a payload no `TFMessage` decoder will accept, which is
 * the outcome to want.
 */
object TransformCodec : LcmCodec<LcmTransform> {
    override val typeName = "geometry_msgs.Transform"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_TRANSFORM

    override fun encodeInto(w: LcmWriter, value: LcmTransform) {
        Vector3Codec.encodeInto(w, value.translation)
        QuaternionCodec.encodeInto(w, value.rotation)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmTransform(Vector3Codec.decodeFrom(r), QuaternionCodec.decodeFrom(r))
}

/** `geometry_msgs.TransformStamped` — `Header header, string child_frame_id, Transform`. */
object TransformStampedCodec : LcmCodec<LcmTransformStamped> {
    override val typeName = "geometry_msgs.TransformStamped"
    override val fingerprint = LcmFingerprints.GEOMETRY_MSGS_TRANSFORM_STAMPED

    override fun encodeInto(w: LcmWriter, value: LcmTransformStamped) {
        HeaderCodec.encodeInto(w, value.header)
        w.writeString(value.childFrameId)
        TransformCodec.encodeInto(w, value.transform)
    }

    override fun decodeFrom(r: LcmReader) = LcmTransformStamped(
        HeaderCodec.decodeFrom(r),
        r.readString(),
        TransformCodec.decodeFrom(r),
    )
}

// ---------------------------------------------------------------------------
// tf2_msgs
// ---------------------------------------------------------------------------

/**
 * `tf2_msgs.TFMessage` — **`int32 transforms_length` then the edges, and no header at all.**
 *
 * The type is the array. Unlike [PathCodec] there is nothing after the length but the elements,
 * so a length written from anywhere other than the list would produce a message that decodes into
 * a truncated or over-read tree — which is why the count is derived here and is not a field.
 */
object TfMessageCodec : LcmCodec<LcmTfMessage> {
    override val typeName = "tf2_msgs.TFMessage"
    override val fingerprint = LcmFingerprints.TF2_MSGS_TF_MESSAGE

    override fun encodeInto(w: LcmWriter, value: LcmTfMessage) {
        w.writeInt(value.transforms.size)
        for (t in value.transforms) TransformStampedCodec.encodeInto(w, t)
    }

    override fun decodeFrom(r: LcmReader): LcmTfMessage {
        val count = r.readInt()
        if (count < 0) throw LcmDecodeException("$typeName: negative transforms_length $count")
        val out = ArrayList<LcmTransformStamped>(minOf(count, 1024))
        for (i in 0 until count) out.add(TransformStampedCodec.decodeFrom(r))
        return LcmTfMessage(out)
    }
}

// ---------------------------------------------------------------------------
// foxglove_msgs
// ---------------------------------------------------------------------------

/**
 * `foxglove_msgs.CompressedVideo` — **`int32 data_length`, `builtin_interfaces.Time`,
 * `string frame_id`, the bytes, `string format`.**
 *
 * Note the shape: unlike every other variable-length type here the length is the *first* field
 * and the body sits in the middle, between two strings. And unlike every other type here the
 * body is the aircraft's own H.264 and is copied rather than converted — see
 * [LcmCompressedVideo].
 */
object CompressedVideoCodec : LcmCodec<LcmCompressedVideo> {
    override val typeName = "foxglove_msgs.CompressedVideo"
    override val fingerprint = LcmFingerprints.FOXGLOVE_MSGS_COMPRESSED_VIDEO

    override fun encodeInto(w: LcmWriter, value: LcmCompressedVideo) {
        w.writeInt(value.data.size)
        BuiltinTimeCodec.encodeInto(w, value.timestamp)
        w.writeString(value.frameId)
        w.writeBytes(value.data)
        w.writeString(value.format)
    }

    override fun decodeFrom(r: LcmReader): LcmCompressedVideo {
        val length = r.readInt()
        if (length < 0) throw LcmDecodeException("$typeName: negative data_length $length")
        val timestamp = BuiltinTimeCodec.decodeFrom(r)
        val frameId = r.readString()
        val data = r.readBytes(length)
        return LcmCompressedVideo(timestamp, frameId, data, r.readString())
    }

    /**
     * A complete payload, written **straight out of a caller's buffer** at `[offset, offset+length)`.
     *
     * The video path's entry point, and the reason it exists is one allocation per frame. MSDK
     * delivers an access unit as a window into a buffer it reuses, and the obvious shape —
     * `copyOfRange` into an [LcmCompressedVideo], then encode — copies ~17 kB twice at 43 fps, so
     * 1.46 MB/s of memcpy on the thread that is decoding video. **The LCM message *is* the copy**:
     * `writeBytes` puts the bytes into a buffer this call owns, before it returns, so the caller's
     * array is free the moment it does. One copy, not two, and no 17 kB garbage per frame.
     *
     * The caller's contract is `video/RawFrameSink`'s: the buffer is valid for the duration of the
     * call and no longer. That is satisfied here by construction rather than by discipline.
     */
    fun encodeSlice(
        timestamp: LcmTime,
        frameId: String,
        data: ByteArray,
        offset: Int,
        length: Int,
        format: String,
    ): ByteArray {
        val w = LcmWriter(encodedSize(length, frameId, format))
        w.writeFingerprint(fingerprint)
        w.writeInt(length)
        BuiltinTimeCodec.encodeInto(w, timestamp)
        w.writeString(frameId)
        w.writeBytes(data, offset, length)
        w.writeString(format)
        return w.toByteArray()
    }

    /**
     * The encoded size of a frame carrying [dataLength] bytes, without encoding it.
     *
     * Exists so the video path can price a message before deciding to build one, so [encodeSlice]
     * can size its buffer exactly and never grow it, and so the bandwidth arithmetic in
     * `docs/measurements/` is computed from the codec rather than estimated beside it.
     */
    fun encodedSize(dataLength: Int, frameId: String, format: String): Int =
        LcmWire.FINGERPRINT_BYTES +
            4 + // data_length
            8 + // builtin_interfaces.Time
            4 + frameId.toByteArray(Charsets.UTF_8).size + 1 +
            dataLength +
            4 + format.toByteArray(Charsets.UTF_8).size + 1
}

// ---------------------------------------------------------------------------
// vision_msgs
// ---------------------------------------------------------------------------

/** `vision_msgs.ObjectHypothesis` — `string class_id, double score`. */
object ObjectHypothesisCodec : LcmCodec<LcmObjectHypothesis> {
    override val typeName = "vision_msgs.ObjectHypothesis"
    override val fingerprint = LcmFingerprints.VISION_MSGS_OBJECT_HYPOTHESIS

    override fun encodeInto(w: LcmWriter, value: LcmObjectHypothesis) {
        w.writeString(value.classId)
        w.writeDouble(value.score)
    }

    override fun decodeFrom(r: LcmReader) = LcmObjectHypothesis(r.readString(), r.readDouble())
}

/** `vision_msgs.ObjectHypothesisWithPose` — `ObjectHypothesis, PoseWithCovariance`. */
object ObjectHypothesisWithPoseCodec : LcmCodec<LcmObjectHypothesisWithPose> {
    override val typeName = "vision_msgs.ObjectHypothesisWithPose"
    override val fingerprint = LcmFingerprints.VISION_MSGS_OBJECT_HYPOTHESIS_WITH_POSE

    override fun encodeInto(w: LcmWriter, value: LcmObjectHypothesisWithPose) {
        ObjectHypothesisCodec.encodeInto(w, value.hypothesis)
        PoseWithCovarianceCodec.encodeInto(w, value.pose)
    }

    override fun decodeFrom(r: LcmReader) = LcmObjectHypothesisWithPose(
        ObjectHypothesisCodec.decodeFrom(r),
        PoseWithCovarianceCodec.decodeFrom(r),
    )
}

/**
 * `vision_msgs.BoundingBox3D` — `Pose center, Vector3 size`.
 *
 * The `size` is a `Vector3` where the `center`'s position is a `Point`. Byte-identical, and the
 * distinction is the same one [TransformCodec] carries: reaching for the wrong one would compile.
 */
object BoundingBox3DCodec : LcmCodec<LcmBoundingBox3D> {
    override val typeName = "vision_msgs.BoundingBox3D"
    override val fingerprint = LcmFingerprints.VISION_MSGS_BOUNDING_BOX_3D

    override fun encodeInto(w: LcmWriter, value: LcmBoundingBox3D) {
        PoseCodec.encodeInto(w, value.center)
        Vector3Codec.encodeInto(w, value.size)
    }

    override fun decodeFrom(r: LcmReader) =
        LcmBoundingBox3D(PoseCodec.decodeFrom(r), Vector3Codec.decodeFrom(r))
}

/**
 * `vision_msgs.Detection3D` — **`int32 results_length` first, then `header`, then the
 * hypotheses, then `bbox`, then `id`.**
 *
 * The third type in this file whose length field is hoisted ahead of the header, and the only one
 * with fields *after* the array: a length that disagreed with the list would not truncate the
 * message, it would decode `bbox` out of the tail of a hypothesis and `id` out of `bbox`. Which
 * is why the count is derived from [LcmDetection3D.results] here and is not a field there.
 */
object Detection3DCodec : LcmCodec<LcmDetection3D> {
    override val typeName = "vision_msgs.Detection3D"
    override val fingerprint = LcmFingerprints.VISION_MSGS_DETECTION_3D

    override fun encodeInto(w: LcmWriter, value: LcmDetection3D) {
        w.writeInt(value.results.size)
        HeaderCodec.encodeInto(w, value.header)
        for (r in value.results) ObjectHypothesisWithPoseCodec.encodeInto(w, r)
        BoundingBox3DCodec.encodeInto(w, value.bbox)
        w.writeString(value.id)
    }

    override fun decodeFrom(r: LcmReader): LcmDetection3D {
        val count = r.readInt()
        if (count < 0) throw LcmDecodeException("$typeName: negative results_length $count")
        val header = HeaderCodec.decodeFrom(r)
        val results = ArrayList<LcmObjectHypothesisWithPose>(minOf(count, 1024))
        for (i in 0 until count) results.add(ObjectHypothesisWithPoseCodec.decodeFrom(r))
        return LcmDetection3D(header, results, BoundingBox3DCodec.decodeFrom(r), r.readString())
    }
}

/**
 * `vision_msgs.Detection3DArray` — **`int32 detections_length` first, then `header`, then the
 * detections.**
 *
 * `nav_msgs.Path`'s shape exactly, one type further out: a hoisted length, a header, and nothing
 * after the array. So unlike [Detection3DCodec] a wrong count here truncates rather than shifting
 * — which is the *less* dangerous of the two failures and still not one to have, so the count is
 * derived from [LcmDetection3DArray.detections] and is not a field.
 */
object Detection3DArrayCodec : LcmCodec<LcmDetection3DArray> {
    override val typeName = "vision_msgs.Detection3DArray"
    override val fingerprint = LcmFingerprints.VISION_MSGS_DETECTION_3D_ARRAY

    override fun encodeInto(w: LcmWriter, value: LcmDetection3DArray) {
        w.writeInt(value.detections.size)
        HeaderCodec.encodeInto(w, value.header)
        for (d in value.detections) Detection3DCodec.encodeInto(w, d)
    }

    override fun decodeFrom(r: LcmReader): LcmDetection3DArray {
        val count = r.readInt()
        if (count < 0) throw LcmDecodeException("$typeName: negative detections_length $count")
        val header = HeaderCodec.decodeFrom(r)
        val out = ArrayList<LcmDetection3D>(minOf(count, 1024))
        for (i in 0 until count) out.add(Detection3DCodec.decodeFrom(r))
        return LcmDetection3DArray(header, out)
    }
}

// ---------------------------------------------------------------------------
// nav_msgs
// ---------------------------------------------------------------------------

/**
 * `nav_msgs.Odometry` — `Header, string child_frame_id, PoseWithCovariance,
 * TwistWithCovariance`.
 *
 * Note `child_frame_id` sits *between* the header and the pose, not at the end.
 */
object OdometryCodec : LcmCodec<LcmOdometry> {
    override val typeName = "nav_msgs.Odometry"
    override val fingerprint = LcmFingerprints.NAV_MSGS_ODOMETRY

    override fun encodeInto(w: LcmWriter, value: LcmOdometry) {
        HeaderCodec.encodeInto(w, value.header)
        w.writeString(value.childFrameId)
        PoseWithCovarianceCodec.encodeInto(w, value.pose)
        TwistWithCovarianceCodec.encodeInto(w, value.twist)
    }

    override fun decodeFrom(r: LcmReader) = LcmOdometry(
        HeaderCodec.decodeFrom(r),
        r.readString(),
        PoseWithCovarianceCodec.decodeFrom(r),
        TwistWithCovarianceCodec.decodeFrom(r),
    )
}

/**
 * `nav_msgs.Path` — **`int32 poses_length` first, then `header`, then the poses.**
 *
 * The length before the header is lcm-gen's hoisting of the array size field, not
 * a mistake: the `.lcm` struct declares `poses_length` ahead of everything it
 * sizes. Getting this backwards produces a message that decodes as a `Path` with
 * an absurd pose count, which is why it has its own fixture.
 */
object PathCodec : LcmCodec<LcmPath> {
    override val typeName = "nav_msgs.Path"
    override val fingerprint = LcmFingerprints.NAV_MSGS_PATH

    override fun encodeInto(w: LcmWriter, value: LcmPath) {
        w.writeInt(value.poses.size)
        HeaderCodec.encodeInto(w, value.header)
        for (p in value.poses) PoseStampedCodec.encodeInto(w, p)
    }

    override fun decodeFrom(r: LcmReader): LcmPath {
        val count = r.readInt()
        if (count < 0) throw LcmDecodeException("$typeName: negative poses_length $count")
        val header = HeaderCodec.decodeFrom(r)
        val poses = ArrayList<LcmPoseStamped>(minOf(count, 1024))
        for (i in 0 until count) poses.add(PoseStampedCodec.decodeFrom(r))
        return LcmPath(header, poses)
    }
}

// ---------------------------------------------------------------------------
// sensor_msgs
// ---------------------------------------------------------------------------

/** `sensor_msgs.NavSatStatus` — `int8 status, int16 service`. */
object NavSatStatusCodec : LcmCodec<LcmNavSatStatus> {
    override val typeName = "sensor_msgs.NavSatStatus"
    override val fingerprint = LcmFingerprints.SENSOR_MSGS_NAV_SAT_STATUS

    override fun encodeInto(w: LcmWriter, value: LcmNavSatStatus) {
        w.writeByte(value.status.toInt())
        w.writeShort(value.service.toInt())
    }

    override fun decodeFrom(r: LcmReader) = LcmNavSatStatus(r.readByte(), r.readShort())
}

/** `sensor_msgs.NavSatFix` — the `datum`, `gps_location` and `gps_goal` channels. */
object NavSatFixCodec : LcmCodec<LcmNavSatFix> {
    override val typeName = "sensor_msgs.NavSatFix"
    override val fingerprint = LcmFingerprints.SENSOR_MSGS_NAV_SAT_FIX

    override fun encodeInto(w: LcmWriter, value: LcmNavSatFix) {
        HeaderCodec.encodeInto(w, value.header)
        NavSatStatusCodec.encodeInto(w, value.status)
        w.writeDouble(value.latitude)
        w.writeDouble(value.longitude)
        w.writeDouble(value.altitude)
        w.writeCovariance(value.positionCovariance, COVARIANCE_SIZE_9, typeName)
        w.writeByte(value.positionCovarianceType.toInt())
    }

    override fun decodeFrom(r: LcmReader) = LcmNavSatFix(
        HeaderCodec.decodeFrom(r),
        NavSatStatusCodec.decodeFrom(r),
        r.readDouble(),
        r.readDouble(),
        r.readDouble(),
        r.readCovariance(COVARIANCE_SIZE_9),
        r.readByte(),
    )
}

/** `sensor_msgs.RegionOfInterest` — four `int32`s and a `boolean`. */
object RegionOfInterestCodec : LcmCodec<LcmRegionOfInterest> {
    override val typeName = "sensor_msgs.RegionOfInterest"
    override val fingerprint = LcmFingerprints.SENSOR_MSGS_REGION_OF_INTEREST

    override fun encodeInto(w: LcmWriter, value: LcmRegionOfInterest) {
        w.writeInt(value.xOffset)
        w.writeInt(value.yOffset)
        w.writeInt(value.height)
        w.writeInt(value.width)
        w.writeBoolean(value.doRectify)
    }

    override fun decodeFrom(r: LcmReader) = LcmRegionOfInterest(
        r.readInt(), r.readInt(), r.readInt(), r.readInt(), r.readBoolean(),
    )
}

/**
 * `sensor_msgs.CameraInfo` — **`D_length` before the header, and `height` before `width`.**
 *
 * Two orderings nobody expects, both lcm-gen's and both pinned by a fixture. The `D` *body* is
 * written after `distortion_model`, far from its own length — the same split-in-two shape
 * [BatteryStateCodec] has, and for the same reason.
 */
object CameraInfoCodec : LcmCodec<LcmCameraInfo> {
    override val typeName = "sensor_msgs.CameraInfo"
    override val fingerprint = LcmFingerprints.SENSOR_MSGS_CAMERA_INFO

    override fun encodeInto(w: LcmWriter, value: LcmCameraInfo) {
        w.writeInt(value.d.size)
        HeaderCodec.encodeInto(w, value.header)
        w.writeInt(value.height)
        w.writeInt(value.width)
        w.writeString(value.distortionModel)
        for (v in value.d) w.writeDouble(v)
        w.writeCovariance(value.k, MATRIX_SIZE_9, "$typeName.K")
        w.writeCovariance(value.r, MATRIX_SIZE_9, "$typeName.R")
        w.writeCovariance(value.p, MATRIX_SIZE_12, "$typeName.P")
        w.writeInt(value.binningX)
        w.writeInt(value.binningY)
        RegionOfInterestCodec.encodeInto(w, value.roi)
    }

    override fun decodeFrom(r: LcmReader): LcmCameraInfo {
        val dLength = r.readInt()
        if (dLength < 0) throw LcmDecodeException("$typeName: negative D_length $dLength")
        val header = HeaderCodec.decodeFrom(r)
        val height = r.readInt()
        val width = r.readInt()
        val model = r.readString()
        val d = ArrayList<Double>(minOf(dLength, 1024))
        for (i in 0 until dLength) d.add(r.readDouble())
        return LcmCameraInfo(
            header = header,
            height = height,
            width = width,
            distortionModel = model,
            d = d,
            k = r.readCovariance(MATRIX_SIZE_9),
            r = r.readCovariance(MATRIX_SIZE_9),
            p = r.readCovariance(MATRIX_SIZE_12),
            binningX = r.readInt(),
            binningY = r.readInt(),
            roi = RegionOfInterestCodec.decodeFrom(r),
        )
    }
}

/** `sensor_msgs.Imu` — three quantities, each followed by its own `double[9]`. */
object ImuCodec : LcmCodec<LcmImu> {
    override val typeName = "sensor_msgs.Imu"
    override val fingerprint = LcmFingerprints.SENSOR_MSGS_IMU

    override fun encodeInto(w: LcmWriter, value: LcmImu) {
        HeaderCodec.encodeInto(w, value.header)
        QuaternionCodec.encodeInto(w, value.orientation)
        w.writeCovariance(value.orientationCovariance, COVARIANCE_SIZE_9, "$typeName.orientation")
        Vector3Codec.encodeInto(w, value.angularVelocity)
        w.writeCovariance(value.angularVelocityCovariance, COVARIANCE_SIZE_9, "$typeName.angular_velocity")
        Vector3Codec.encodeInto(w, value.linearAcceleration)
        w.writeCovariance(value.linearAccelerationCovariance, COVARIANCE_SIZE_9, "$typeName.linear_acceleration")
    }

    override fun decodeFrom(r: LcmReader) = LcmImu(
        HeaderCodec.decodeFrom(r),
        QuaternionCodec.decodeFrom(r),
        r.readCovariance(COVARIANCE_SIZE_9),
        Vector3Codec.decodeFrom(r),
        r.readCovariance(COVARIANCE_SIZE_9),
        Vector3Codec.decodeFrom(r),
        r.readCovariance(COVARIANCE_SIZE_9),
    )
}

/**
 * `sensor_msgs.BatteryState` — the `battery` channel.
 *
 * **Both cell-array lengths are written before the header**, in declaration
 * order: `cell_voltage_length`, then `cell_temperature_length`, then everything
 * else. The array *bodies* come much later, after the `present` flag. Two
 * separated halves of the same field is the shape lcm-gen produces and the shape
 * the fixture proves.
 */
object BatteryStateCodec : LcmCodec<LcmBatteryState> {
    override val typeName = "sensor_msgs.BatteryState"
    override val fingerprint = LcmFingerprints.SENSOR_MSGS_BATTERY_STATE

    override fun encodeInto(w: LcmWriter, value: LcmBatteryState) {
        w.writeInt(value.cellVoltage.size)
        w.writeInt(value.cellTemperature.size)
        HeaderCodec.encodeInto(w, value.header)
        w.writeFloat(value.voltage)
        w.writeFloat(value.temperature)
        w.writeFloat(value.current)
        w.writeFloat(value.charge)
        w.writeFloat(value.capacity)
        w.writeFloat(value.designCapacity)
        w.writeFloat(value.percentage)
        w.writeByte(value.powerSupplyStatus.toInt())
        w.writeByte(value.powerSupplyHealth.toInt())
        w.writeByte(value.powerSupplyTechnology.toInt())
        w.writeBoolean(value.present)
        for (v in value.cellVoltage) w.writeFloat(v)
        for (v in value.cellTemperature) w.writeFloat(v)
        w.writeString(value.location)
        w.writeString(value.serialNumber)
    }

    override fun decodeFrom(r: LcmReader): LcmBatteryState {
        val cellVoltageLength = r.readInt()
        val cellTemperatureLength = r.readInt()
        if (cellVoltageLength < 0 || cellTemperatureLength < 0) {
            throw LcmDecodeException(
                "$typeName: negative cell array length ($cellVoltageLength, $cellTemperatureLength)"
            )
        }
        val header = HeaderCodec.decodeFrom(r)
        val voltage = r.readFloat()
        val temperature = r.readFloat()
        val current = r.readFloat()
        val charge = r.readFloat()
        val capacity = r.readFloat()
        val designCapacity = r.readFloat()
        val percentage = r.readFloat()
        val status = r.readByte()
        val health = r.readByte()
        val technology = r.readByte()
        val present = r.readBoolean()
        val cellVoltage = ArrayList<Float>(minOf(cellVoltageLength, 1024))
        for (i in 0 until cellVoltageLength) cellVoltage.add(r.readFloat())
        val cellTemperature = ArrayList<Float>(minOf(cellTemperatureLength, 1024))
        for (i in 0 until cellTemperatureLength) cellTemperature.add(r.readFloat())
        return LcmBatteryState(
            header = header,
            voltage = voltage,
            temperature = temperature,
            current = current,
            charge = charge,
            capacity = capacity,
            designCapacity = designCapacity,
            percentage = percentage,
            powerSupplyStatus = status,
            powerSupplyHealth = health,
            powerSupplyTechnology = technology,
            present = present,
            cellVoltage = cellVoltage,
            cellTemperature = cellTemperature,
            location = r.readString(),
            serialNumber = r.readString(),
        )
    }
}

// ---------------------------------------------------------------------------
// diagnostic_msgs
// ---------------------------------------------------------------------------

/** `diagnostic_msgs.KeyValue` — two strings, in declaration order. */
object KeyValueCodec : LcmCodec<LcmKeyValue> {
    override val typeName = "diagnostic_msgs.KeyValue"
    override val fingerprint = LcmFingerprints.DIAGNOSTIC_MSGS_KEY_VALUE

    override fun encodeInto(w: LcmWriter, value: LcmKeyValue) {
        w.writeString(value.key)
        w.writeString(value.value)
    }

    override fun decodeFrom(r: LcmReader) = LcmKeyValue(r.readString(), r.readString())
}

/**
 * `diagnostic_msgs.DiagnosticStatus` — `int32 values_length, int8 level, string name, string
 * message, string hardware_id, KeyValue values[]`.
 *
 * **The length field comes first, ahead of `level`**, because that is where lcm-gen hoisted it in
 * the `.lcm` declaration — not next to the array. Getting that wrong produces bytes that decode as
 * something plausible and wrong, which is why the fixture in `android/app/src/test/resources/lcm/`
 * is generated by DiMOS's own bindings rather than by this file.
 */
object DiagnosticStatusCodec : LcmCodec<LcmDiagnosticStatus> {
    override val typeName = "diagnostic_msgs.DiagnosticStatus"
    override val fingerprint = LcmFingerprints.DIAGNOSTIC_MSGS_DIAGNOSTIC_STATUS

    override fun encodeInto(w: LcmWriter, value: LcmDiagnosticStatus) {
        w.writeInt(value.values.size)
        w.writeByte(value.level.toInt())
        w.writeString(value.name)
        w.writeString(value.message)
        w.writeString(value.hardwareId)
        for (kv in value.values) KeyValueCodec.encodeInto(w, kv)
    }

    override fun decodeFrom(r: LcmReader): LcmDiagnosticStatus {
        val count = r.readInt()
        if (count < 0) throw LcmDecodeException("$typeName: negative values_length $count")
        val level = r.readByte()
        val name = r.readString()
        val message = r.readString()
        val hardwareId = r.readString()
        val values = ArrayList<LcmKeyValue>(minOf(count, 1024))
        for (i in 0 until count) values.add(KeyValueCodec.decodeFrom(r))
        return LcmDiagnosticStatus(level, name, message, hardwareId, values)
    }
}

/**
 * `diagnostic_msgs.DiagnosticArray` — `int32 status_length, Header header, DiagnosticStatus
 * status[]`. Carries `warnings`.
 */
object DiagnosticArrayCodec : LcmCodec<LcmDiagnosticArray> {
    override val typeName = "diagnostic_msgs.DiagnosticArray"
    override val fingerprint = LcmFingerprints.DIAGNOSTIC_MSGS_DIAGNOSTIC_ARRAY

    override fun encodeInto(w: LcmWriter, value: LcmDiagnosticArray) {
        w.writeInt(value.status.size)
        HeaderCodec.encodeInto(w, value.header)
        for (s in value.status) DiagnosticStatusCodec.encodeInto(w, s)
    }

    override fun decodeFrom(r: LcmReader): LcmDiagnosticArray {
        val count = r.readInt()
        if (count < 0) throw LcmDecodeException("$typeName: negative status_length $count")
        val header = HeaderCodec.decodeFrom(r)
        val out = ArrayList<LcmDiagnosticStatus>(minOf(count, 1024))
        for (i in 0 until count) out.add(DiagnosticStatusCodec.decodeFrom(r))
        return LcmDiagnosticArray(header, out)
    }
}
