// GENERATED by `python -m dimos.gateway.msgs --write` from dimos/msgs/ and dimos_lcm: do not edit.
// Every dimos message's LCM codec, by name, fingerprint, LCM channel or zenoh key. msgs.js is this file as
// plain JS (GET /dimos/msgs.js).
//
//     import { decodeMessage, geometry_msgs } from "../../dimos/msgs.js"
//     z.subscribe("dimos/odom/**", {}, (m) => console.log(decodeMessage(m)))
//     z.put(geometry_msgs.Twist.zenohKey("dimos/cmd_vel"), geometry_msgs.Twist.encode({ linear: { x: 0.3 } }))
//
// dimos messages with no LCM schema (decode them with register()):
//   nav_msgs.LineSegments3D (dimos/msgs/nav_msgs/LineSegments3D.py:LineSegments3D): hand-written, no dimos_lcm.nav_msgs.LineSegments3D class
//   sensor_msgs.ImuInfo (dimos/msgs/sensor_msgs/ImuInfo.py:ImuInfo): hand-written, no dimos_lcm.sensor_msgs.ImuInfo class
//   sensor_msgs.JointCommand (dimos/msgs/sensor_msgs/JointCommand.py:JointCommand): hand-written, no dimos_lcm.sensor_msgs.JointCommand class
//   sensor_msgs.MotorCommandArray (dimos/msgs/sensor_msgs/MotorCommandArray.py:MotorCommandArray): hand-written, no dimos_lcm.sensor_msgs.MotorCommandArray class
//   sensor_msgs.RobotState (dimos/msgs/sensor_msgs/RobotState.py:RobotState): hand-written, no dimos_lcm.sensor_msgs.RobotState class
//   trajectory_msgs.JointTrajectory (dimos/msgs/trajectory_msgs/JointTrajectory.py:JointTrajectory): hand-written, its own fingerprint 2b3c4d5e6f708192 (dimos_lcm.trajectory_msgs.JointTrajectory is another message of the same name, fingerprint ae3a209832c6d386)
//   trajectory_msgs.TrajectoryPoint (dimos/msgs/trajectory_msgs/TrajectoryPoint.py:TrajectoryPoint): hand-written, no dimos_lcm.trajectory_msgs.TrajectoryPoint class
//   trajectory_msgs.TrajectoryStatus (dimos/msgs/trajectory_msgs/TrajectoryStatus.py:TrajectoryStatus): hand-written, no dimos_lcm.trajectory_msgs.TrajectoryStatus class
//   visualization_msgs.EntityMarkers (dimos/msgs/visualization_msgs/EntityMarkers.py:EntityMarkers): hand-written, no dimos_lcm.visualization_msgs.EntityMarkers class

// ---- runtime.ts ----
// The LCM codec behind msgs.ts: decodes and encodes any message from its schema (rows exported from the generated
// dimos_lcm class by dimos/web/lcm_codec.py export_schema), so the generated part of msgs.ts is data, not code.
// generate() in __init__.py pastes this file into msgs.ts verbatim; it stays a module of its own so `deno check` can
// read it alone. Decoded values are plain objects with the fields in wire order (the *_length count fields too):
// byte[] and int8_t[] are views into the frame (copy them to keep them past the frame's buffer), other number arrays
// fresh typed arrays, int64_t a bigint.

/** [field, type, dims]: dims null for a scalar, [n] for a fixed array, ["<count field>"] for a variable one. */
export type Field = [name: string, type: string, dims: (number | string)[] | null]
export type MsgValue = Record<string, unknown>

/** What a value to encode may hold for a decoded type: any field left out is zero, "" or empty, number arrays may
 * be plain arrays, and a variable array's count field is filled in from the array. */
export type MsgInput<T> = T extends bigint ? bigint | number
    : T extends BigInt64Array ? ArrayLike<bigint | number>
    : T extends Uint8Array | Int8Array | Int16Array | Int32Array | Float32Array | Float64Array ? ArrayLike<number>
    : T extends (infer E)[] ? MsgInput<E>[]
    : T extends object ? { [K in keyof T]?: MsgInput<T[K]> }
    : T

/** One message type: decode a frame (its 8-byte fingerprint first), encode a value into one. */
export interface MsgType<T = MsgValue> {
    /** "<package>.<Type>", e.g. "geometry_msgs.PoseStamped" */
    readonly name: string
    /** the 16 hex chars every frame of this type starts with (null for a registered type without one) */
    readonly fingerprint: string | null
    decode(bytes: Uint8Array): T
    encode(value: MsgInput<T>): Uint8Array
    /** the zenoh key dimos publishes `topic` on: "dimos/cmd_vel" -> "dimos/cmd_vel/geometry_msgs.Twist" */
    zenohKey(topic: string): string
    /** the LCM channel dimos publishes `topic` on: "/cmd_vel" -> "/cmd_vel#geometry_msgs.Twist" */
    lcmChannel(topic: string): string
}

/** A zenoh-gateway client Message, or anything with its key and payload bytes. */
export interface KeyedSample {
    key: string
    bytes: Uint8Array
    kind?: string
}

const SIZE: Record<string, number> = {
    int8_t: 1,
    int16_t: 2,
    int32_t: 4,
    int64_t: 8,
    float: 4,
    double: 8,
    boolean: 1,
    byte: 1,
}
const TYPED: Record<string, { new (n: number): ArrayLike<unknown> & { [i: number]: unknown } }> = {
    int16_t: Int16Array,
    int32_t: Int32Array,
    int64_t: BigInt64Array,
    float: Float32Array,
    double: Float64Array,
}
// fatal: corrupt bytes fail the decode instead of turning into U+FFFD; ignoreBOM: a leading U+FEFF is kept (as Python does)
const utf8Decoder = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true })
const utf8Encoder = new TextEncoder()
const TYPE_NAME = /^[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*$/

type Reader = { view: DataView; bytes: Uint8Array; off: number }
type FieldDecoder = (r: Reader, out: MsgValue) => void

class Writer {
    bytes = new Uint8Array(256)
    view = new DataView(this.bytes.buffer)
    off = 0
    need(n: number): void {
        if (this.off + n <= this.bytes.length) {
            return
        }
        const grown = new Uint8Array(Math.max(this.bytes.length * 2, this.off + n))
        grown.set(this.bytes)
        this.bytes = grown
        this.view = new DataView(grown.buffer)
    }
}

function readScalar(r: Reader, type: string): unknown {
    const { view } = r
    const at = r.off
    if (type === "string") {
        const len = view.getInt32(at, false) // counts the trailing NUL
        if (len < 1 || at + 4 + len > r.bytes.byteLength) {
            throw new Error(`bad string length ${len} at ${at}`)
        }
        r.off = at + 4 + len
        return utf8Decoder.decode(r.bytes.subarray(at + 4, at + 3 + len))
    }
    r.off = at + SIZE[type]
    switch (type) {
        case "double":
            return view.getFloat64(at, false)
        case "float":
            return view.getFloat32(at, false)
        case "int64_t":
            return view.getBigInt64(at, false)
        case "int32_t":
            return view.getInt32(at, false)
        case "int16_t":
            return view.getInt16(at, false)
        case "int8_t":
            return view.getInt8(at)
        case "byte":
            return view.getUint8(at)
        case "boolean":
            return view.getUint8(at) !== 0
    }
    throw new Error(`unknown LCM primitive ${type}`)
}

function writeScalar(w: Writer, type: string, value: unknown): void {
    if (type === "string") {
        const text = utf8Encoder.encode(value === undefined ? "" : String(value))
        w.need(5 + text.length)
        w.view.setInt32(w.off, text.length + 1, false)
        w.bytes.set(text, w.off + 4)
        w.bytes[w.off + 4 + text.length] = 0
        w.off += 5 + text.length
        return
    }
    const at = w.off
    w.need(SIZE[type])
    w.off += SIZE[type]
    const v = w.view
    switch (type) {
        case "double":
            return v.setFloat64(at, Number(value ?? 0), false)
        case "float":
            return v.setFloat32(at, Number(value ?? 0), false)
        case "int64_t":
            return v.setBigInt64(at, typeof value === "bigint" ? value : BigInt(Math.trunc(Number(value ?? 0))), false)
        case "int32_t":
            return v.setInt32(at, Number(value ?? 0), false)
        case "int16_t":
            return v.setInt16(at, Number(value ?? 0), false)
        case "int8_t":
            return v.setInt8(at, Number(value ?? 0))
        case "byte":
            return v.setUint8(at, Number(value ?? 0))
        case "boolean":
            return v.setUint8(at, value ? 1 : 0)
    }
    throw new Error(`unknown LCM primitive ${type}`)
}

/** Decoders and encoders compiled from a table of struct schemas, each struct once. */
class Codec {
    private decoders = new Map<string, FieldDecoder[] | null>()
    constructor(private structs: Record<string, Field[]>) {}

    private rows(name: string): Field[] {
        const rows = this.structs[name]
        if (!Array.isArray(rows)) {
            throw new Error(`no schema for struct ${name}`)
        }
        return rows
    }

    private isPrimitive(type: string): boolean {
        return type === "string" || Object.hasOwn(SIZE, type)
    }

    private count(dim: number | string, value: MsgValue): number {
        const n = typeof dim === "number" ? dim : value[dim]
        if (typeof n !== "number" || n < 0 || !Number.isInteger(n)) {
            throw new Error(`bad array length ${String(n)}`)
        }
        return n
    }

    fields(name: string): FieldDecoder[] {
        const done = this.decoders.get(name)
        if (done) {
            return done
        }
        if (done === null) {
            throw new Error(`recursive struct ${name}`)
        }
        this.decoders.set(name, null)
        const decoders = this.rows(name).map(([field, type, dims]): FieldDecoder => {
            // a computed __proto__ key would set the record's prototype
            if (field === "__proto__") {
                throw new Error(`field __proto__ is not supported (${name})`)
            }
            const primitive = this.isPrimitive(type)
            const one = primitive ? (r: Reader) => readScalar(r, type) : (r: Reader) => this.readStruct(r, type)
            if (dims === null) {
                return (r, out) => {
                    out[field] = one(r)
                }
            }
            if (dims.length !== 1) {
                throw new Error(`multi-dimensional arrays are not supported (${name}.${field})`)
            }
            const [dim] = dims
            return (r, out) => {
                const n = this.count(dim, out)
                const size = primitive ? SIZE[type] ?? 5 : 1 // every string is at least 5 bytes
                if (r.off + n * size > r.bytes.byteLength) {
                    throw new Error(`${name}.${field}: ${n} x ${type} overruns the frame`)
                }
                if (type === "byte" || type === "int8_t") {
                    const view = r.bytes.subarray(r.off, r.off + n)
                    out[field] = type === "byte" ? view : new Int8Array(view.buffer as ArrayBuffer, view.byteOffset, n)
                    r.off += n
                    return
                }
                const Typed = TYPED[type]
                const items = Typed ? new Typed(n) : new Array(n)
                for (let i = 0; i < n; i++) {
                    items[i] = one(r)
                }
                out[field] = items
            }
        })
        this.decoders.set(name, decoders)
        return decoders
    }

    readStruct(r: Reader, name: string): MsgValue {
        const out: MsgValue = {}
        for (const decode of this.fields(name)) {
            decode(r, out)
        }
        return out
    }

    writeStruct(w: Writer, name: string, value: MsgValue): void {
        const rows = this.rows(name)
        const counts: Record<string, number> = {}
        for (const [field, type, dims] of rows) {
            const item = value?.[field]
            const primitive = this.isPrimitive(type)
            const one = (x: unknown) =>
                primitive ? writeScalar(w, type, x) : this.writeStruct(w, type, (x ?? {}) as MsgValue)
            if (dims === null) {
                // a count field: the length of the arrays it counts, when they are given
                const counted = rows.filter(([, , d]) => d?.[0] === field).map(([f]) => value?.[f])
                    .filter((a) => a !== undefined) as ArrayLike<unknown>[]
                if (counted.length > 0) {
                    const n = counted[0].length
                    if (counted.some((a) => a.length !== n)) {
                        throw new Error(`${name}: the arrays counted by ${field} differ in length`)
                    }
                    counts[field] = n
                    writeScalar(w, type, n)
                } else {
                    counts[field] = Number(item ?? 0)
                    one(item)
                }
                continue
            }
            if (dims.length !== 1) {
                throw new Error(`multi-dimensional arrays are not supported (${name}.${field})`)
            }
            const [dim] = dims
            const n = typeof dim === "number" ? dim : counts[dim]
            const items = (item ?? []) as ArrayLike<unknown>
            if (item !== undefined && items.length !== n) {
                throw new Error(`${name}.${field}: ${items.length} items, the schema wants ${n}`)
            }
            for (let i = 0; i < n; i++) {
                one(items[i])
            }
        }
    }
}

function fingerprintBytes(hex: string): Uint8Array {
    return Uint8Array.from({ length: 8 }, (_, i) => parseInt(hex.slice(i * 2, i * 2 + 2), 16))
}

function fingerprintOf(bytes: Uint8Array): string {
    if (bytes.byteLength < 8) {
        throw new Error("frame shorter than its 8-byte fingerprint")
    }
    return Array.from(bytes.subarray(0, 8), (b) => b.toString(16).padStart(2, "0")).join("")
}

function withName<T>(name: string, fingerprint: string | null, decode: (bytes: Uint8Array) => T, encode: (value: MsgInput<T>) => Uint8Array): MsgType<T> {
    return Object.freeze({
        name,
        fingerprint,
        decode,
        encode,
        zenohKey: (topic: string) => `${topic.replace(/\/+$/, "")}/${name}`,
        lcmChannel: (topic: string) => `${topic}#${name}`,
    })
}

/** The message types of a schema table, by name and by fingerprint, plus the names known to have no schema. */
export function createRegistry(structs: Record<string, Field[]>, types: Record<string, string>, missing: Record<string, string>) {
    const codec = new Codec(structs)
    const byName = new Map<string, MsgType<unknown>>()
    const byFingerprint = new Map<string, MsgType<unknown>[]>()
    const unsupported = new Map(Object.entries(missing))

    const add = (type: MsgType<unknown>) => {
        byName.set(type.name, type)
        unsupported.delete(type.name)
        if (type.fingerprint !== null) {
            const list = (byFingerprint.get(type.fingerprint) ?? []).filter((t) => t.name !== type.name)
            byFingerprint.set(type.fingerprint, [type, ...list])
        }
        return type
    }

    for (const [name, fingerprint] of Object.entries(types)) {
        const expected = fingerprintBytes(fingerprint)
        add(withName<MsgValue>(
            name,
            fingerprint,
            (bytes) => {
                for (let i = 0; i < 8; i++) {
                    if (bytes[i] !== expected[i]) {
                        throw new Error(`fingerprint mismatch: the frame is not a ${name}`)
                    }
                }
                const r = { view: new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength), bytes, off: 8 }
                const value = codec.readStruct(r, name)
                if (r.off !== bytes.byteLength) {
                    throw new Error(`${name}: ${bytes.byteLength - r.off} trailing bytes`)
                }
                return value
            },
            (value) => {
                const w = new Writer()
                w.need(8)
                w.bytes.set(expected)
                w.off = 8
                codec.writeStruct(w, name, value as MsgValue)
                return w.bytes.slice(0, w.off)
            },
        ))
    }

    /** The "<package>.<Type>" a channel or key names: after the last "#" of an LCM channel ("/odom#nav_msgs.Odometry"),
     * else its last "/" segment when that looks like one (the zenoh key "dimos/odom/nav_msgs.Odometry"). */
    const typeOfChannel = (channel: string): string | undefined => {
        const hash = channel.lastIndexOf("#")
        const name = hash >= 0 ? channel.slice(hash + 1) : channel.slice(channel.lastIndexOf("/") + 1)
        return TYPE_NAME.test(name) ? name : undefined
    }

    /** A message type by name; throws for one without a schema, with the reason. */
    const lookup = (name: string): MsgType<unknown> => {
        const type = byName.get(name)
        if (type) {
            return type
        }
        const reason = unsupported.get(name)
        throw new Error(reason ? `${name} has no LCM schema (${reason}): register() a decoder for it` : `unknown message type ${name}`)
    }

    /** Decode a frame by its fingerprint. Types with the same layout share one (geometry_msgs.Point and Vector3), and
     * decode the same; the most recently registered wins. */
    const decode = (bytes: Uint8Array): unknown => {
        const fingerprint = fingerprintOf(bytes)
        const type = byFingerprint.get(fingerprint)?.[0]
        if (!type) {
            throw new Error(`no message type has fingerprint ${fingerprint}`)
        }
        return type.decode(bytes)
    }

    /** Decode a frame from an LCM channel or zenoh key: the type the name carries wins over the fingerprint
     * (dimos's own trajectory_msgs.JointTrajectory shares its name, not its layout, with the ROS one); a channel
     * without a type, or with one this module has never heard of, decodes by fingerprint. */
    const decodeChannel = (channel: string, bytes: Uint8Array): unknown => {
        const name = typeOfChannel(channel)
        if (name !== undefined && (byName.has(name) || unsupported.has(name))) {
            return lookup(name).decode(bytes)
        }
        return decode(bytes)
    }

    /** Decode a zenoh-gateway Message (`z.subscribe(key, {}, (m) => decodeMessage(m))`): undefined for a delete. */
    const decodeMessage = (message: KeyedSample): unknown =>
        message.kind === "delete" ? undefined : decodeChannel(message.key, message.bytes)

    /** Add or replace a message type: a hand-written dimos message, or an app's own. `decode` gets the whole frame;
     * `fingerprint` (16 hex chars) lets decode() find it, null leaves it to channel names. */
    const register = <T = unknown>(
        name: string,
        fingerprint: string | null,
        decodeFn: (bytes: Uint8Array) => T,
        encodeFn?: (value: MsgInput<T>) => Uint8Array,
    ): MsgType<T> => {
        if (!TYPE_NAME.test(name)) {
            throw new Error(`register: the name must be "<package>.<Type>", got ${JSON.stringify(name)}`)
        }
        if (fingerprint !== null && !/^[0-9a-f]{16}$/.test(fingerprint)) {
            throw new Error(`register: the fingerprint must be 16 lowercase hex chars or null, got ${JSON.stringify(fingerprint)}`)
        }
        const encode = encodeFn ?? (() => {
            throw new Error(`${name} was registered without an encoder`)
        })
        return add(withName(name, fingerprint, decodeFn, encode) as MsgType<unknown>) as MsgType<T>
    }

    return {
        decode,
        decodeChannel,
        decodeMessage,
        typeOfChannel,
        lookup,
        register,
        /** every type this module decodes, sorted (registered ones included) */
        getTypeNames: (): string[] => [...byName.keys()].sort(),
        /** dimos's messages with no LCM schema, and why: "sensor_msgs.JointCommand" -> its reason */
        getMissingTypes: (): Record<string, string> => Object.fromEntries(unsupported),
    }
}

// ---- schemas ----

const STRUCTS: Record<string, Field[]> = {
    "builtin_interfaces.Time": [["sec", "int32_t", null], ["nanosec", "int32_t", null]],
    "control_msgs.ControlValues": [["source", "string", null], ["source_ts", "double", null], ["epoch", "int64_t", null], ["sequence", "int64_t", null], ["interface_names_length", "int32_t", null], ["values_length", "int32_t", null], ["interface_names", "string", ["interface_names_length"]], ["values", "double", ["values_length"]]],
    "foxglove_msgs.CompressedVideo": [["data_length", "int32_t", null], ["timestamp", "builtin_interfaces.Time", null], ["frame_id", "string", null], ["data", "byte", ["data_length"]], ["format", "string", null]],
    "geometry_msgs.Point": [["x", "double", null], ["y", "double", null], ["z", "double", null]],
    "geometry_msgs.PointStamped": [["header", "std_msgs.Header", null], ["point", "geometry_msgs.Point", null]],
    "geometry_msgs.Pose": [["position", "geometry_msgs.Point", null], ["orientation", "geometry_msgs.Quaternion", null]],
    "geometry_msgs.PoseArray": [["poses_length", "int32_t", null], ["header", "std_msgs.Header", null], ["poses", "geometry_msgs.Pose", ["poses_length"]]],
    "geometry_msgs.PoseStamped": [["header", "std_msgs.Header", null], ["pose", "geometry_msgs.Pose", null]],
    "geometry_msgs.PoseWithCovariance": [["pose", "geometry_msgs.Pose", null], ["covariance", "double", [36]]],
    "geometry_msgs.PoseWithCovarianceStamped": [["header", "std_msgs.Header", null], ["pose", "geometry_msgs.PoseWithCovariance", null]],
    "geometry_msgs.Quaternion": [["x", "double", null], ["y", "double", null], ["z", "double", null], ["w", "double", null]],
    "geometry_msgs.Transform": [["translation", "geometry_msgs.Vector3", null], ["rotation", "geometry_msgs.Quaternion", null]],
    "geometry_msgs.TransformStamped": [["header", "std_msgs.Header", null], ["child_frame_id", "string", null], ["transform", "geometry_msgs.Transform", null]],
    "geometry_msgs.Twist": [["linear", "geometry_msgs.Vector3", null], ["angular", "geometry_msgs.Vector3", null]],
    "geometry_msgs.TwistStamped": [["header", "std_msgs.Header", null], ["twist", "geometry_msgs.Twist", null]],
    "geometry_msgs.TwistWithCovariance": [["twist", "geometry_msgs.Twist", null], ["covariance", "double", [36]]],
    "geometry_msgs.TwistWithCovarianceStamped": [["header", "std_msgs.Header", null], ["twist", "geometry_msgs.TwistWithCovariance", null]],
    "geometry_msgs.Vector3": [["x", "double", null], ["y", "double", null], ["z", "double", null]],
    "geometry_msgs.Wrench": [["force", "geometry_msgs.Vector3", null], ["torque", "geometry_msgs.Vector3", null]],
    "geometry_msgs.WrenchStamped": [["header", "std_msgs.Header", null], ["wrench", "geometry_msgs.Wrench", null]],
    "nav_msgs.MapMetaData": [["map_load_time", "std_msgs.Time", null], ["resolution", "float", null], ["width", "int32_t", null], ["height", "int32_t", null], ["origin", "geometry_msgs.Pose", null]],
    "nav_msgs.OccupancyGrid": [["data_length", "int32_t", null], ["header", "std_msgs.Header", null], ["info", "nav_msgs.MapMetaData", null], ["data", "int8_t", ["data_length"]]],
    "nav_msgs.Odometry": [["header", "std_msgs.Header", null], ["child_frame_id", "string", null], ["pose", "geometry_msgs.PoseWithCovariance", null], ["twist", "geometry_msgs.TwistWithCovariance", null]],
    "nav_msgs.Path": [["poses_length", "int32_t", null], ["header", "std_msgs.Header", null], ["poses", "geometry_msgs.PoseStamped", ["poses_length"]]],
    "sensor_msgs.BatteryState": [["cell_voltage_length", "int32_t", null], ["cell_temperature_length", "int32_t", null], ["header", "std_msgs.Header", null], ["voltage", "float", null], ["temperature", "float", null], ["current", "float", null], ["charge", "float", null], ["capacity", "float", null], ["design_capacity", "float", null], ["percentage", "float", null], ["power_supply_status", "byte", null], ["power_supply_health", "byte", null], ["power_supply_technology", "byte", null], ["present", "boolean", null], ["cell_voltage", "float", ["cell_voltage_length"]], ["cell_temperature", "float", ["cell_temperature_length"]], ["location", "string", null], ["serial_number", "string", null]],
    "sensor_msgs.CameraInfo": [["D_length", "int32_t", null], ["header", "std_msgs.Header", null], ["height", "int32_t", null], ["width", "int32_t", null], ["distortion_model", "string", null], ["D", "double", ["D_length"]], ["K", "double", [9]], ["R", "double", [9]], ["P", "double", [12]], ["binning_x", "int32_t", null], ["binning_y", "int32_t", null], ["roi", "sensor_msgs.RegionOfInterest", null]],
    "sensor_msgs.CompressedImage": [["data_length", "int32_t", null], ["header", "std_msgs.Header", null], ["format", "string", null], ["data", "byte", ["data_length"]]],
    "sensor_msgs.Image": [["data_length", "int32_t", null], ["header", "std_msgs.Header", null], ["height", "int32_t", null], ["width", "int32_t", null], ["encoding", "string", null], ["is_bigendian", "byte", null], ["step", "int32_t", null], ["data", "byte", ["data_length"]]],
    "sensor_msgs.Imu": [["header", "std_msgs.Header", null], ["orientation", "geometry_msgs.Quaternion", null], ["orientation_covariance", "double", [9]], ["angular_velocity", "geometry_msgs.Vector3", null], ["angular_velocity_covariance", "double", [9]], ["linear_acceleration", "geometry_msgs.Vector3", null], ["linear_acceleration_covariance", "double", [9]]],
    "sensor_msgs.JointState": [["name_length", "int32_t", null], ["position_length", "int32_t", null], ["velocity_length", "int32_t", null], ["effort_length", "int32_t", null], ["header", "std_msgs.Header", null], ["name", "string", ["name_length"]], ["position", "double", ["position_length"]], ["velocity", "double", ["velocity_length"]], ["effort", "double", ["effort_length"]]],
    "sensor_msgs.Joy": [["axes_length", "int32_t", null], ["buttons_length", "int32_t", null], ["header", "std_msgs.Header", null], ["axes", "float", ["axes_length"]], ["buttons", "int32_t", ["buttons_length"]]],
    "sensor_msgs.PointCloud2": [["fields_length", "int32_t", null], ["data_length", "int32_t", null], ["header", "std_msgs.Header", null], ["height", "int32_t", null], ["width", "int32_t", null], ["fields", "sensor_msgs.PointField", ["fields_length"]], ["is_bigendian", "boolean", null], ["point_step", "int32_t", null], ["row_step", "int32_t", null], ["data", "byte", ["data_length"]], ["is_dense", "boolean", null]],
    "sensor_msgs.PointField": [["name", "string", null], ["offset", "int32_t", null], ["datatype", "byte", null], ["count", "int32_t", null]],
    "sensor_msgs.RegionOfInterest": [["x_offset", "int32_t", null], ["y_offset", "int32_t", null], ["height", "int32_t", null], ["width", "int32_t", null], ["do_rectify", "boolean", null]],
    "std_msgs.Bool": [["data", "boolean", null]],
    "std_msgs.Float32": [["data", "float", null]],
    "std_msgs.Header": [["seq", "int32_t", null], ["stamp", "std_msgs.Time", null], ["frame_id", "string", null]],
    "std_msgs.Int32": [["data", "int32_t", null]],
    "std_msgs.Int8": [["data", "int8_t", null]],
    "std_msgs.String": [["data", "string", null]],
    "std_msgs.Time": [["sec", "int32_t", null], ["nsec", "int32_t", null]],
    "std_msgs.UInt32": [["data", "int32_t", null]],
    "tf2_msgs.TFMessage": [["transforms_length", "int32_t", null], ["transforms", "geometry_msgs.TransformStamped", ["transforms_length"]]],
    "vision_msgs.BoundingBox2D": [["center", "vision_msgs.Pose2D", null], ["size_x", "double", null], ["size_y", "double", null]],
    "vision_msgs.BoundingBox2DArray": [["boxes_length", "int32_t", null], ["header", "std_msgs.Header", null], ["boxes", "vision_msgs.BoundingBox2D", ["boxes_length"]]],
    "vision_msgs.BoundingBox3D": [["center", "geometry_msgs.Pose", null], ["size", "geometry_msgs.Vector3", null]],
    "vision_msgs.BoundingBox3DArray": [["boxes_length", "int32_t", null], ["header", "std_msgs.Header", null], ["boxes", "vision_msgs.BoundingBox3D", ["boxes_length"]]],
    "vision_msgs.Detection2D": [["results_length", "int32_t", null], ["header", "std_msgs.Header", null], ["results", "vision_msgs.ObjectHypothesisWithPose", ["results_length"]], ["bbox", "vision_msgs.BoundingBox2D", null], ["id", "string", null]],
    "vision_msgs.Detection2DArray": [["detections_length", "int32_t", null], ["header", "std_msgs.Header", null], ["detections", "vision_msgs.Detection2D", ["detections_length"]]],
    "vision_msgs.Detection3D": [["results_length", "int32_t", null], ["header", "std_msgs.Header", null], ["results", "vision_msgs.ObjectHypothesisWithPose", ["results_length"]], ["bbox", "vision_msgs.BoundingBox3D", null], ["id", "string", null]],
    "vision_msgs.Detection3DArray": [["detections_length", "int32_t", null], ["header", "std_msgs.Header", null], ["detections", "vision_msgs.Detection3D", ["detections_length"]]],
    "vision_msgs.ObjectHypothesis": [["class_id", "string", null], ["score", "double", null]],
    "vision_msgs.ObjectHypothesisWithPose": [["hypothesis", "vision_msgs.ObjectHypothesis", null], ["pose", "geometry_msgs.PoseWithCovariance", null]],
    "vision_msgs.Point2D": [["x", "double", null], ["y", "double", null]],
    "vision_msgs.Pose2D": [["position", "vision_msgs.Point2D", null], ["theta", "double", null]],
}
const TYPES: Record<string, string> = {
    "control_msgs.ControlValues": "31b3ec9631ab499f",
    "foxglove_msgs.CompressedVideo": "2217b46eefbf7b05",
    "geometry_msgs.Point": "ae7e5fba5eeca11e",
    "geometry_msgs.PointStamped": "9cd764738ea629af",
    "geometry_msgs.Pose": "245634ae2ab17b76",
    "geometry_msgs.PoseArray": "3755f9405735978e",
    "geometry_msgs.PoseStamped": "6a82696458c279a0",
    "geometry_msgs.PoseWithCovariance": "ce6428b127d11b5a",
    "geometry_msgs.PoseWithCovarianceStamped": "be9e516a5301b969",
    "geometry_msgs.Quaternion": "363bdd3bf9180a2b",
    "geometry_msgs.Twist": "2e7c07d7cdf7e027",
    "geometry_msgs.TwistStamped": "9cd2bcbe6cb2a7c0",
    "geometry_msgs.TwistWithCovariance": "b439635a59217509",
    "geometry_msgs.TwistWithCovarianceStamped": "a84d73c38305d185",
    "geometry_msgs.Vector3": "ae7e5fba5eeca11e",
    "geometry_msgs.Wrench": "ccfb0646cebc17c4",
    "geometry_msgs.WrenchStamped": "d31bb4c714d07137",
    "nav_msgs.OccupancyGrid": "e7dfd179cdfc3b65",
    "nav_msgs.Odometry": "94e17f94648cf0e4",
    "nav_msgs.Path": "c3ae62acb35793e2",
    "sensor_msgs.BatteryState": "7e3961fd10438489",
    "sensor_msgs.CameraInfo": "afb501b00707a02a",
    "sensor_msgs.CompressedImage": "b8d011c10412b9a1",
    "sensor_msgs.Image": "535cface1f4f5717",
    "sensor_msgs.Imu": "31ab205c8dd57aa8",
    "sensor_msgs.JointState": "ccefa8a492b967e3",
    "sensor_msgs.Joy": "a0f07abc86c1684c",
    "sensor_msgs.PointCloud2": "f5eb3da1c2853175",
    "std_msgs.Bool": "1ebef06a50950e3e",
    "std_msgs.Float32": "0adc26b8f0546dd3",
    "std_msgs.Header": "2fdb11453be64af7",
    "std_msgs.Int32": "2cbcf9f7ea91023e",
    "std_msgs.Int8": "21d34305fdbb4415",
    "std_msgs.String": "21bf37099b9d5e15",
    "std_msgs.UInt32": "2cbcf9f7ea91023e",
    "tf2_msgs.TFMessage": "c2b8a1c33a8923ec",
    "vision_msgs.BoundingBox2DArray": "89ae9c19ce1bbb6a",
    "vision_msgs.BoundingBox3DArray": "943b9c9caeede310",
    "vision_msgs.Detection2D": "b4e48d74d9bf4510",
    "vision_msgs.Detection2DArray": "d4e87e619f4e9c86",
    "vision_msgs.Detection3D": "bf718df7ba916cb6",
    "vision_msgs.Detection3DArray": "ea027f6760f2ebd2",
}
const MISSING: Record<string, string> = {
    "nav_msgs.LineSegments3D": "hand-written, no dimos_lcm.nav_msgs.LineSegments3D class [dimos/msgs/nav_msgs/LineSegments3D.py:LineSegments3D]",
    "sensor_msgs.ImuInfo": "hand-written, no dimos_lcm.sensor_msgs.ImuInfo class [dimos/msgs/sensor_msgs/ImuInfo.py:ImuInfo]",
    "sensor_msgs.JointCommand": "hand-written, no dimos_lcm.sensor_msgs.JointCommand class [dimos/msgs/sensor_msgs/JointCommand.py:JointCommand]",
    "sensor_msgs.MotorCommandArray": "hand-written, no dimos_lcm.sensor_msgs.MotorCommandArray class [dimos/msgs/sensor_msgs/MotorCommandArray.py:MotorCommandArray]",
    "sensor_msgs.RobotState": "hand-written, no dimos_lcm.sensor_msgs.RobotState class [dimos/msgs/sensor_msgs/RobotState.py:RobotState]",
    "trajectory_msgs.JointTrajectory": "hand-written, its own fingerprint 2b3c4d5e6f708192 (dimos_lcm.trajectory_msgs.JointTrajectory is another message of the same name, fingerprint ae3a209832c6d386) [dimos/msgs/trajectory_msgs/JointTrajectory.py:JointTrajectory]",
    "trajectory_msgs.TrajectoryPoint": "hand-written, no dimos_lcm.trajectory_msgs.TrajectoryPoint class [dimos/msgs/trajectory_msgs/TrajectoryPoint.py:TrajectoryPoint]",
    "trajectory_msgs.TrajectoryStatus": "hand-written, no dimos_lcm.trajectory_msgs.TrajectoryStatus class [dimos/msgs/trajectory_msgs/TrajectoryStatus.py:TrajectoryStatus]",
    "visualization_msgs.EntityMarkers": "hand-written, no dimos_lcm.visualization_msgs.EntityMarkers class [dimos/msgs/visualization_msgs/EntityMarkers.py:EntityMarkers]",
}

const registry = createRegistry(STRUCTS, TYPES, MISSING)
export const { decode, decodeChannel, decodeMessage, typeOfChannel, lookup, register, getTypeNames, getMissingTypes } =
    registry

export namespace builtin_interfaces {
    export interface Time {
        sec: number
        nanosec: number
    }
}
export namespace control_msgs {
    export interface ControlValues {
        source: string
        source_ts: number
        epoch: bigint
        sequence: bigint
        interface_names_length: number
        values_length: number
        interface_names: string[]
        values: Float64Array
    }
    export const ControlValues = lookup("control_msgs.ControlValues") as MsgType<ControlValues>
}
export namespace foxglove_msgs {
    export interface CompressedVideo {
        data_length: number
        timestamp: builtin_interfaces.Time
        frame_id: string
        data: Uint8Array
        format: string
    }
    export const CompressedVideo = lookup("foxglove_msgs.CompressedVideo") as MsgType<CompressedVideo>
}
export namespace geometry_msgs {
    export interface Point {
        x: number
        y: number
        z: number
    }
    export const Point = lookup("geometry_msgs.Point") as MsgType<Point>
    export interface PointStamped {
        header: std_msgs.Header
        point: geometry_msgs.Point
    }
    export const PointStamped = lookup("geometry_msgs.PointStamped") as MsgType<PointStamped>
    export interface Pose {
        position: geometry_msgs.Point
        orientation: geometry_msgs.Quaternion
    }
    export const Pose = lookup("geometry_msgs.Pose") as MsgType<Pose>
    export interface PoseArray {
        poses_length: number
        header: std_msgs.Header
        poses: geometry_msgs.Pose[]
    }
    export const PoseArray = lookup("geometry_msgs.PoseArray") as MsgType<PoseArray>
    export interface PoseStamped {
        header: std_msgs.Header
        pose: geometry_msgs.Pose
    }
    export const PoseStamped = lookup("geometry_msgs.PoseStamped") as MsgType<PoseStamped>
    export interface PoseWithCovariance {
        pose: geometry_msgs.Pose
        covariance: Float64Array
    }
    export const PoseWithCovariance = lookup("geometry_msgs.PoseWithCovariance") as MsgType<PoseWithCovariance>
    export interface PoseWithCovarianceStamped {
        header: std_msgs.Header
        pose: geometry_msgs.PoseWithCovariance
    }
    export const PoseWithCovarianceStamped = lookup("geometry_msgs.PoseWithCovarianceStamped") as MsgType<PoseWithCovarianceStamped>
    export interface Quaternion {
        x: number
        y: number
        z: number
        w: number
    }
    export const Quaternion = lookup("geometry_msgs.Quaternion") as MsgType<Quaternion>
    export interface Transform {
        translation: geometry_msgs.Vector3
        rotation: geometry_msgs.Quaternion
    }
    export interface TransformStamped {
        header: std_msgs.Header
        child_frame_id: string
        transform: geometry_msgs.Transform
    }
    export interface Twist {
        linear: geometry_msgs.Vector3
        angular: geometry_msgs.Vector3
    }
    export const Twist = lookup("geometry_msgs.Twist") as MsgType<Twist>
    export interface TwistStamped {
        header: std_msgs.Header
        twist: geometry_msgs.Twist
    }
    export const TwistStamped = lookup("geometry_msgs.TwistStamped") as MsgType<TwistStamped>
    export interface TwistWithCovariance {
        twist: geometry_msgs.Twist
        covariance: Float64Array
    }
    export const TwistWithCovariance = lookup("geometry_msgs.TwistWithCovariance") as MsgType<TwistWithCovariance>
    export interface TwistWithCovarianceStamped {
        header: std_msgs.Header
        twist: geometry_msgs.TwistWithCovariance
    }
    export const TwistWithCovarianceStamped = lookup("geometry_msgs.TwistWithCovarianceStamped") as MsgType<TwistWithCovarianceStamped>
    export interface Vector3 {
        x: number
        y: number
        z: number
    }
    export const Vector3 = lookup("geometry_msgs.Vector3") as MsgType<Vector3>
    export interface Wrench {
        force: geometry_msgs.Vector3
        torque: geometry_msgs.Vector3
    }
    export const Wrench = lookup("geometry_msgs.Wrench") as MsgType<Wrench>
    export interface WrenchStamped {
        header: std_msgs.Header
        wrench: geometry_msgs.Wrench
    }
    export const WrenchStamped = lookup("geometry_msgs.WrenchStamped") as MsgType<WrenchStamped>
}
export namespace nav_msgs {
    export interface MapMetaData {
        map_load_time: std_msgs.Time
        resolution: number
        width: number
        height: number
        origin: geometry_msgs.Pose
    }
    export interface OccupancyGrid {
        data_length: number
        header: std_msgs.Header
        info: nav_msgs.MapMetaData
        data: Int8Array
    }
    export const OccupancyGrid = lookup("nav_msgs.OccupancyGrid") as MsgType<OccupancyGrid>
    export interface Odometry {
        header: std_msgs.Header
        child_frame_id: string
        pose: geometry_msgs.PoseWithCovariance
        twist: geometry_msgs.TwistWithCovariance
    }
    export const Odometry = lookup("nav_msgs.Odometry") as MsgType<Odometry>
    export interface Path {
        poses_length: number
        header: std_msgs.Header
        poses: geometry_msgs.PoseStamped[]
    }
    export const Path = lookup("nav_msgs.Path") as MsgType<Path>
}
export namespace sensor_msgs {
    export interface BatteryState {
        cell_voltage_length: number
        cell_temperature_length: number
        header: std_msgs.Header
        voltage: number
        temperature: number
        current: number
        charge: number
        capacity: number
        design_capacity: number
        percentage: number
        power_supply_status: number
        power_supply_health: number
        power_supply_technology: number
        present: boolean
        cell_voltage: Float32Array
        cell_temperature: Float32Array
        location: string
        serial_number: string
    }
    export const BatteryState = lookup("sensor_msgs.BatteryState") as MsgType<BatteryState>
    export interface CameraInfo {
        D_length: number
        header: std_msgs.Header
        height: number
        width: number
        distortion_model: string
        D: Float64Array
        K: Float64Array
        R: Float64Array
        P: Float64Array
        binning_x: number
        binning_y: number
        roi: sensor_msgs.RegionOfInterest
    }
    export const CameraInfo = lookup("sensor_msgs.CameraInfo") as MsgType<CameraInfo>
    export interface CompressedImage {
        data_length: number
        header: std_msgs.Header
        format: string
        data: Uint8Array
    }
    export const CompressedImage = lookup("sensor_msgs.CompressedImage") as MsgType<CompressedImage>
    export interface Image {
        data_length: number
        header: std_msgs.Header
        height: number
        width: number
        encoding: string
        is_bigendian: number
        step: number
        data: Uint8Array
    }
    export const Image = lookup("sensor_msgs.Image") as MsgType<Image>
    export interface Imu {
        header: std_msgs.Header
        orientation: geometry_msgs.Quaternion
        orientation_covariance: Float64Array
        angular_velocity: geometry_msgs.Vector3
        angular_velocity_covariance: Float64Array
        linear_acceleration: geometry_msgs.Vector3
        linear_acceleration_covariance: Float64Array
    }
    export const Imu = lookup("sensor_msgs.Imu") as MsgType<Imu>
    export interface JointState {
        name_length: number
        position_length: number
        velocity_length: number
        effort_length: number
        header: std_msgs.Header
        name: string[]
        position: Float64Array
        velocity: Float64Array
        effort: Float64Array
    }
    export const JointState = lookup("sensor_msgs.JointState") as MsgType<JointState>
    export interface Joy {
        axes_length: number
        buttons_length: number
        header: std_msgs.Header
        axes: Float32Array
        buttons: Int32Array
    }
    export const Joy = lookup("sensor_msgs.Joy") as MsgType<Joy>
    export interface PointCloud2 {
        fields_length: number
        data_length: number
        header: std_msgs.Header
        height: number
        width: number
        fields: sensor_msgs.PointField[]
        is_bigendian: boolean
        point_step: number
        row_step: number
        data: Uint8Array
        is_dense: boolean
    }
    export const PointCloud2 = lookup("sensor_msgs.PointCloud2") as MsgType<PointCloud2>
    export interface PointField {
        name: string
        offset: number
        datatype: number
        count: number
    }
    export interface RegionOfInterest {
        x_offset: number
        y_offset: number
        height: number
        width: number
        do_rectify: boolean
    }
}
export namespace std_msgs {
    export interface Bool {
        data: boolean
    }
    export const Bool = lookup("std_msgs.Bool") as MsgType<Bool>
    export interface Float32 {
        data: number
    }
    export const Float32 = lookup("std_msgs.Float32") as MsgType<Float32>
    export interface Header {
        seq: number
        stamp: std_msgs.Time
        frame_id: string
    }
    export const Header = lookup("std_msgs.Header") as MsgType<Header>
    export interface Int32 {
        data: number
    }
    export const Int32 = lookup("std_msgs.Int32") as MsgType<Int32>
    export interface Int8 {
        data: number
    }
    export const Int8 = lookup("std_msgs.Int8") as MsgType<Int8>
    export interface String {
        data: string
    }
    export const String = lookup("std_msgs.String") as MsgType<String>
    export interface Time {
        sec: number
        nsec: number
    }
    export interface UInt32 {
        data: number
    }
    export const UInt32 = lookup("std_msgs.UInt32") as MsgType<UInt32>
}
export namespace tf2_msgs {
    export interface TFMessage {
        transforms_length: number
        transforms: geometry_msgs.TransformStamped[]
    }
    export const TFMessage = lookup("tf2_msgs.TFMessage") as MsgType<TFMessage>
}
export namespace vision_msgs {
    export interface BoundingBox2D {
        center: vision_msgs.Pose2D
        size_x: number
        size_y: number
    }
    export interface BoundingBox2DArray {
        boxes_length: number
        header: std_msgs.Header
        boxes: vision_msgs.BoundingBox2D[]
    }
    export const BoundingBox2DArray = lookup("vision_msgs.BoundingBox2DArray") as MsgType<BoundingBox2DArray>
    export interface BoundingBox3D {
        center: geometry_msgs.Pose
        size: geometry_msgs.Vector3
    }
    export interface BoundingBox3DArray {
        boxes_length: number
        header: std_msgs.Header
        boxes: vision_msgs.BoundingBox3D[]
    }
    export const BoundingBox3DArray = lookup("vision_msgs.BoundingBox3DArray") as MsgType<BoundingBox3DArray>
    export interface Detection2D {
        results_length: number
        header: std_msgs.Header
        results: vision_msgs.ObjectHypothesisWithPose[]
        bbox: vision_msgs.BoundingBox2D
        id: string
    }
    export const Detection2D = lookup("vision_msgs.Detection2D") as MsgType<Detection2D>
    export interface Detection2DArray {
        detections_length: number
        header: std_msgs.Header
        detections: vision_msgs.Detection2D[]
    }
    export const Detection2DArray = lookup("vision_msgs.Detection2DArray") as MsgType<Detection2DArray>
    export interface Detection3D {
        results_length: number
        header: std_msgs.Header
        results: vision_msgs.ObjectHypothesisWithPose[]
        bbox: vision_msgs.BoundingBox3D
        id: string
    }
    export const Detection3D = lookup("vision_msgs.Detection3D") as MsgType<Detection3D>
    export interface Detection3DArray {
        detections_length: number
        header: std_msgs.Header
        detections: vision_msgs.Detection3D[]
    }
    export const Detection3DArray = lookup("vision_msgs.Detection3DArray") as MsgType<Detection3DArray>
    export interface ObjectHypothesis {
        class_id: string
        score: number
    }
    export interface ObjectHypothesisWithPose {
        hypothesis: vision_msgs.ObjectHypothesis
        pose: geometry_msgs.PoseWithCovariance
    }
    export interface Point2D {
        x: number
        y: number
    }
    export interface Pose2D {
        position: vision_msgs.Point2D
        theta: number
    }
}
