# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Emit the throwaway cargo crate that becomes the host binary.

The crate is a table of module entries plus three JSON blobs; all the runtime
behaviour lives in `dimos_module::host`, so there is nothing here to debug.
"""

from __future__ import annotations

from collections.abc import Sequence
import json
from pathlib import Path

from dimos.cli.bake.discovery import ModuleInfo, repo_root
from dimos.cli.bake.graph import Graph

GENERATED_HEADER = "// GENERATED BY dimos bake — do not edit."

_CARGO_TEMPLATE = """# GENERATED BY dimos bake — do not edit.
[workspace]

[package]
name = "{host}"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "{host}"
path = "src/main.rs"

[dependencies]
{dependencies}

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
"""

_MAIN_TEMPLATE = """{header}
use dimos_module::{{host_main, HostSpec, ModuleEntry}};

static MODULES: &[ModuleEntry] = &[
{entries}
];

static SUPPRESS: &[&str] = &[
{suppress}
];

static SPEC: HostSpec = HostSpec {{
    name: "{host}",
    modules: MODULES,
    default_topics: include_str!("default_topics.json"),
    default_suppress: SUPPRESS,
    default_qos: include_str!("default_qos.json"),
    graph_json: include_str!("graph.json"),
}};

fn main() {{
    host_main(&SPEC)
}}
"""


def crate_dir(host: str, root: Path | None = None) -> Path:
    """Where the generated crate for `host` lives."""
    return (root or repo_root()) / "target" / "dimos-bake" / host


def _dependencies(modules: Sequence[ModuleInfo], root: Path) -> str:
    lines = [f'dimos-module = {{ path = "{root / "native" / "rust" / "dimos-module"}" }}']
    for module in modules:
        # default-features off drops pyo3, whose libpython symbols would break a
        # static link and are dead weight in a host either way.
        lines.append(
            f'{module.crate_name} = {{ path = "{module.crate_dir}", default-features = false }}'
        )
    return "\n".join(lines)


def _entries(modules: Sequence[ModuleInfo]) -> str:
    lines = []
    for module in modules:
        call = f'    ModuleEntry::new::<{module.rust_path}>("{module.id}")'
        if module.threads != 1:
            call += f".threads({module.threads})"
        if module.nice is not None:
            call += f".nice({module.nice})"
        lines.append(call + ",")
    return "\n".join(lines)


def render_cargo_toml(host: str, modules: Sequence[ModuleInfo], root: Path | None = None) -> str:
    return _CARGO_TEMPLATE.format(
        host=host, dependencies=_dependencies(modules, root or repo_root())
    )


def render_main_rs(host: str, modules: Sequence[ModuleInfo], graph: Graph) -> str:
    suppress = "\n".join(f'    "{topic}",' for topic in graph.suppressed_topics())
    return _MAIN_TEMPLATE.format(
        header=GENERATED_HEADER,
        host=host,
        entries=_entries(modules),
        suppress=suppress,
    )


def generate_crate(
    host: str,
    modules: Sequence[ModuleInfo],
    graph: Graph,
    root: Path | None = None,
) -> Path:
    """Write the generated crate and return its directory."""
    root = root or repo_root()
    directory = crate_dir(host, root)
    src = directory / "src"
    src.mkdir(parents=True, exist_ok=True)

    (directory / "Cargo.toml").write_text(render_cargo_toml(host, modules, root))
    (src / "main.rs").write_text(render_main_rs(host, modules, graph))
    (src / "default_topics.json").write_text(json.dumps(graph.topics(), indent=2) + "\n")
    (src / "default_qos.json").write_text(json.dumps(graph.qos(), indent=2) + "\n")
    (src / "graph.json").write_text(json.dumps(graph.to_json(), indent=2) + "\n")
    return directory
