# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the generated host crate and the builder invocation."""

import json
from pathlib import Path

import pytest

from dimos.cli.bake import BakeError
from dimos.cli.bake.build import artifact_path, build_command
from dimos.cli.bake.codegen import generate_crate, render_cargo_toml, render_main_rs
from dimos.cli.bake.graph import build_graph
from dimos.cli.bake.test_graph import MAPPER, PLANNER, module

GRAPH = build_graph("go2-nav", [MAPPER, PLANNER], suppress=["local_map"])


def test_cargo_toml_pins_absolute_paths_and_drops_default_features():
    toml = render_cargo_toml("go2-nav", [MAPPER, PLANNER], Path("/repo"))
    assert '[[bin]]\nname = "go2-nav"' in toml
    assert 'dimos-module = { path = "/repo/native/rust/dimos-module" }' in toml
    assert 'crate-mapper = { path = "/crates/mapper", default-features = false }' in toml
    assert 'strip = "symbols"' in toml
    # An isolated workspace: the crate lives under the repo's target/ dir.
    assert toml.startswith("# GENERATED BY dimos bake")
    assert "[workspace]" in toml


def test_main_rs_lists_entries_with_their_thread_counts():
    threaded = module("planner", PLANNER.inputs, PLANNER.outputs, threads=2)
    main = render_main_rs("go2-nav", [MAPPER, threaded], GRAPH)
    assert '    ModuleEntry::new::<mapper::module::Thing>("mapper"),' in main
    assert '    ModuleEntry::new::<planner::module::Thing>("planner").threads(2),' in main
    assert '    "dimos/local_map/sensor_msgs.PointCloud2",' in main
    assert main.startswith("// GENERATED BY dimos bake")
    assert 'name: "go2-nav",' in main
    assert 'include_str!("graph.json")' in main


def test_generate_crate_writes_the_blobs_the_host_includes(tmp_path):
    crate = generate_crate("go2-nav", [MAPPER, PLANNER], GRAPH, tmp_path)
    assert crate == tmp_path / "target" / "dimos-bake" / "go2-nav"

    topics = json.loads((crate / "src" / "default_topics.json").read_text())
    assert topics["mapper"]["lidar"] == "dimos/lidar/sensor_msgs.PointCloud2"
    assert topics["planner"]["local_map"] == "dimos/local_map/sensor_msgs.PointCloud2"

    qos = json.loads((crate / "src" / "default_qos.json").read_text())
    assert qos["dimos/local_map/sensor_msgs.PointCloud2"]["congestion_control"] == "drop"

    graph = json.loads((crate / "src" / "graph.json").read_text())
    assert graph["host"] == "go2-nav"
    assert (crate / "Cargo.toml").exists()


def test_generate_crate_is_idempotent(tmp_path):
    first = generate_crate("go2-nav", [MAPPER, PLANNER], GRAPH, tmp_path)
    before = (first / "src" / "main.rs").read_text()
    again = generate_crate("go2-nav", [MAPPER, PLANNER], GRAPH, tmp_path)
    assert (again / "src" / "main.rs").read_text() == before


def test_build_command_per_builder():
    assert build_command("cargo") == ["cargo", "build", "--release"]
    assert build_command("cargo", debug=True) == ["cargo", "build"]
    assert build_command("cross", target="aarch64-unknown-linux-musl") == [
        "cross",
        "build",
        "--release",
        "--target",
        "aarch64-unknown-linux-musl",
    ]
    assert build_command("zigbuild")[:2] == ["cargo", "zigbuild"]
    with pytest.raises(BakeError, match="unknown --builder"):
        build_command("make")


def test_artifact_path_follows_profile_and_target():
    crate = Path("/crate")
    assert artifact_path(crate, "host") == crate / "target" / "release" / "host"
    assert artifact_path(crate, "host", debug=True) == crate / "target" / "debug" / "host"
    assert (
        artifact_path(crate, "host", target="aarch64-unknown-linux-musl")
        == crate / "target" / "aarch64-unknown-linux-musl" / "release" / "host"
    )
