# Copyright 2025-2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Shared plumbing for the skill-verification suite.

Loads manifest.yaml, hands each test a per-skill output directory under
test_outputs/, and renders test_outputs/REVIEW.md from the manifest's review
criteria — tagging which artifacts a run actually produced.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

HERE = Path(__file__).parent
MANIFEST_PATH = HERE / "manifest.yaml"
OUTPUTS_ROOT = HERE / "test_outputs"


def load_manifest() -> dict[str, Any]:
    """Parse manifest.yaml."""
    with MANIFEST_PATH.open() as f:
        return yaml.safe_load(f)


def skills_by_id() -> dict[str, dict[str, Any]]:
    """Manifest skill entries keyed by id."""
    return {s["id"]: s for s in load_manifest()["skills"]}


@dataclass
class SkillOutput:
    """A per-skill output directory plus the review notes a test records.

    A test saves artifacts into ``dir`` and calls :meth:`produced` for each one
    it actually wrote, so REVIEW.md can distinguish produced-this-run artifacts
    from ones only the (skipped) real-data tier would have made.
    """

    skill_id: str
    dir: Path
    _produced: dict[str, str] = field(default_factory=dict)

    def path(self, filename: str) -> Path:
        """Absolute path for an artifact filename inside this skill's dir."""
        return self.dir / filename

    def produced(self, filename: str, note: str = "") -> Path:
        """Record that ``filename`` was written this run; returns its path."""
        self._produced[filename] = note
        return self.path(filename)


class ReviewCollector:
    """Accumulates per-skill produced-artifact records across the session and
    renders test_outputs/REVIEW.md from the manifest."""

    def __init__(self) -> None:
        self._produced: dict[str, dict[str, str]] = {}

    def merge(self, out: SkillOutput) -> None:
        if not out._produced:
            return
        self._produced.setdefault(out.skill_id, {}).update(out._produced)

    def render_markdown(self) -> str:
        manifest = load_manifest()
        by_id = self._produced
        lines: list[str] = []
        lines.append(f"# {manifest['suite']} — review")
        lines.append("")
        lines.append(
            "Generated by the suite. For each skill below, open the listed files "
            "and check them against *what you should see*. A ✅ marks an artifact "
            "this run produced; a ⚪ marks one whose tier was skipped (e.g. a "
            "real-data test with no recording present)."
        )
        lines.append("")
        any_produced = any(by_id.values())
        if not any_produced:
            lines.append("> **No artifacts were produced this run.** Did the suite run?")
            lines.append("")

        for skill in manifest["skills"]:
            sid = skill["id"]
            produced = by_id.get(sid, {})
            lines.append(f"## {sid} — {skill['title']}")
            lines.append("")
            mcp = ", ".join(f"`{s}`" for s in skill.get("mcp_skills") or []) or "—"
            lines.append(f"- **Wishlist item:** {skill['wishlist_item']} ({skill['status']})")
            lines.append(f"- **MCP skills:** {mcp}")
            lines.append(f"- **Tier:** {skill['tier']}"
                         + (f" (marker: `{skill['marker']}`)" if skill.get("marker") else ""))
            lines.append(f"- **Input:** {skill['fixture'].strip()}")
            lines.append("")
            lines.append(f"**What you should see:** {skill['review_summary'].strip()}")
            lines.append("")
            lines.append("| status | file | what to check |")
            lines.append("| --- | --- | --- |")
            for art in skill.get("outputs") or []:
                fname = art["file"]
                mark = "✅" if fname in produced else "⚪"
                rel = f"`{sid}/{fname}`"
                lines.append(f"| {mark} | {rel} | {art['review'].strip()} |")
            lines.append("")

        nc = manifest.get("not_covered") or []
        if nc:
            lines.append("## Not covered")
            lines.append("")
            for entry in nc:
                lines.append(f"- **Item {entry['item']} — {entry['title']}:** {entry['reason'].strip()}")
            lines.append("")
        return "\n".join(lines)

    def write(self) -> Path:
        OUTPUTS_ROOT.mkdir(parents=True, exist_ok=True)
        path = OUTPUTS_ROOT / "REVIEW.md"
        path.write_text(self.render_markdown())
        return path
