include(CMakeFindDependencyMacro)
find_dependency(builtin_interfaces 0.1.0 EXACT)
find_dependency(std_msgs 0.1.0 EXACT)
find_dependency(geometry_msgs 0.1.0 EXACT)
find_dependency(vision_msgs 0.1.0 EXACT)
find_dependency(dimos_msgs 0.1.0 EXACT)
find_dependency(foxglove_msgs 0.1.0 EXACT)
find_dependency(nav_msgs 0.1.0 EXACT)
find_dependency(sensor_msgs 0.1.0 EXACT)
find_dependency(shape_msgs 0.1.0 EXACT)
find_dependency(tf2_msgs 0.1.0 EXACT)
find_dependency(trajectory_msgs 0.1.0 EXACT)
find_dependency(visualization_msgs 0.1.0 EXACT)
if(NOT TARGET dimos_generated::messages)
add_library(dimos_generated::messages INTERFACE IMPORTED)
set_property(TARGET dimos_generated::messages PROPERTY INTERFACE_LINK_LIBRARIES "builtin_interfaces::builtin_interfaces__rosidl_typesupport_fastrtps_cpp;std_msgs::std_msgs__rosidl_typesupport_fastrtps_cpp;geometry_msgs::geometry_msgs__rosidl_typesupport_fastrtps_cpp;vision_msgs::vision_msgs__rosidl_typesupport_fastrtps_cpp;dimos_msgs::dimos_msgs__rosidl_typesupport_fastrtps_cpp;foxglove_msgs::foxglove_msgs__rosidl_typesupport_fastrtps_cpp;nav_msgs::nav_msgs__rosidl_typesupport_fastrtps_cpp;sensor_msgs::sensor_msgs__rosidl_typesupport_fastrtps_cpp;shape_msgs::shape_msgs__rosidl_typesupport_fastrtps_cpp;tf2_msgs::tf2_msgs__rosidl_typesupport_fastrtps_cpp;trajectory_msgs::trajectory_msgs__rosidl_typesupport_fastrtps_cpp;visualization_msgs::visualization_msgs__rosidl_typesupport_fastrtps_cpp")
endif()
