// Regenerates the golden fixture vectors from protocol.ts.
//
// Run from web/:  deno run --allow-write=shared/fixtures shared/fixtures/gen.ts
//
// The vectors pin the byte-level protocol across the TS and Python codecs, so
// changes here are protocol changes and need review on both sides. Vector
// rules: no integral-valued floats (JS renders 1.0 as "1", Python as "1.0")
// and at least one non-ASCII string (pins ensure_ascii=False on the Python
// side). Message literals below are written in canonical field order - the
// same order the Python dataclasses declare.
//
// costmap_frames.json is NOT written here: its payloads are the Python
// encoder's zlib bytes (CompressionStream output differs byte-wise), so it is
// generated by `uv run python -m dimos.web.relay_bridge.gen_costmap_fixtures`.

import {
  CONTROL_CHANNEL,
  encodeControlFrame,
  encodeDataFrame,
  encodeDatagram,
  type FrameHeader,
  type Msg,
  msgFromUnknown,
  PROTOCOL_VERSION,
  TX_CH_MAX_LEN,
  TX_DATA_MAX_BYTES,
  type TxMsg,
} from "../protocol.ts";
import { ManifestError, parseManifest } from "../manifest.ts";

function b64(bytes: Uint8Array): string {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s);
}

const txMsgs: Record<string, TxMsg> = {
  tx_chat: { t: "tx", ch: "human_input", seq: 1, data: { text: "Du-te în bucătărie" } },
  tx_goal: {
    t: "tx",
    ch: "goal_request",
    seq: 2,
    data: { x: 1.25, y: -0.5, yaw: 1.5, frame: "world" },
  },
  tx_command: {
    t: "tx",
    ch: "ui_command",
    seq: 3,
    data: { name: "set_mode", args: { mode: "agent" } },
  },
};

const controlMsgs: Record<string, Msg> = {
  hello_robot: {
    t: "hello",
    v: PROTOCOL_VERSION,
    role: "robot",
    robot: { id: "go2-lab", name: "Go2 Laborator β", model: "unitree-go2" },
    // A fully explicit (normalized) manifest, as the bridge emits it.
    manifest: {
      version: 1,
      channels: [
        {
          ch: "color_image",
          dir: "rx",
          encoding: "jpeg.v1",
          delivery: "latest",
          maxHz: 15.5,
          params: { quality: 75.5 },
        },
        {
          ch: "odom",
          dir: "rx",
          encoding: "pose.json.v1",
          delivery: "reliable",
          maxHz: 20.5,
          params: {},
        },
      ],
      panels: [
        { id: "p0", kind: "video", title: "Camera β", channels: ["color_image"], params: {} },
      ],
      layout: { row: ["p0"] },
      pages: [],
    },
  },
  hello_viewer: { t: "hello", v: PROTOCOL_VERSION, role: "viewer" },
  welcome: { t: "welcome", v: PROTOCOL_VERSION },
  ping: { t: "ping", n: 7, ts: 1752576000.5 },
  pong: { t: "pong", n: 7, ts: 1752576000.5 },
  error_version: {
    t: "error",
    code: "version_mismatch",
    message: `protocol v${PROTOCOL_VERSION} required, versiune neacceptată`,
  },
  robots_two: {
    t: "robots",
    robots: [
      { id: "go2-lab", name: "Go2 Laborator β", model: "unitree-go2" },
      { id: "arm-01", name: "Braț 01", model: "xarm7" },
    ],
  },
  robots_empty: { t: "robots", robots: [] },
  watch: { t: "watch", robotId: "go2-lab" },
  // Deliberately partial (un-normalized) manifest: the relay forwards the
  // robot's manifest verbatim, never normalizing it.
  manifest_reply: {
    t: "manifest",
    robotId: "go2-lab",
    manifest: {
      version: 1,
      channels: [{ ch: "odom", encoding: "pose.json.v1", delivery: "reliable", maxHz: 20.5 }],
      panels: [{ id: "pose", kind: "readout", title: "Poziție", channels: ["odom"] }],
      layout: "pose",
    },
  },
  // Watch reply for a robot that registered without a manifest.
  manifest_reply_bare: { t: "manifest", robotId: "arm-01" },
  sub: { t: "sub", ch: "color_image" },
  unsub: { t: "unsub", ch: "color_image" },
  subs_snapshot: { t: "subs", chs: ["color_image", "odom"], n: 3 },
  subs_empty: { t: "subs", chs: [], n: 4 },
  // Bare lease messages are the viewer-leg shapes (control stream); the
  // gen-stamped robot-bound forms are pinned in teleopMsgs below.
  teleop_start: { t: "teleop_start" },
  teleop_started: { t: "teleop_started" },
  teleop_stop: { t: "teleop_stop" },
  // Generic tx commands (viewer control stream; relay forwards them to the
  // robot unchanged): chat text, a navigation goal, a UI command. The data
  // shapes are what the cockpit's chat/navmap/control panels send.
  tx_chat: txMsgs.tx_chat,
  tx_goal: txMsgs.tx_goal,
  tx_command: txMsgs.tx_command,
};

const teleopMsgs: Record<string, Msg> = {
  twist: { t: "twist", vx: 0.5, vy: 0.25, wz: -0.25, seq: 12, ts: 1752576000.5 },
  stop: { t: "stop", seq: 13, ts: 1752576000.5 },
  // Robot-bound forms: the relay stamps the lease generation.
  twist_gen: { t: "twist", vx: 0.5, vy: 0.25, wz: -0.25, seq: 12, ts: 1752576000.5, gen: 3 },
  stop_gen: { t: "stop", seq: 13, ts: 1752576000.5, gen: 3 },
  teleop_start_gen: { t: "teleop_start", gen: 3 },
  teleop_stop_gen: { t: "teleop_stop", gen: 3 },
};

// Tx validation vectors: `valid` is declared here (the expectation), and
// both msgFromUnknown and msg_from_dict must agree with it. Valid vectors
// also pin their datagram bytes. The cap cases pin byte (not character)
// counting: 447 "é" is 455 characters but 902 bytes.
const dataAtCap = { text: "x".repeat(TX_DATA_MAX_BYTES - '{"text":""}'.length) };
const txCases: Record<string, { message: unknown; valid: boolean }> = {
  tx_chat: { message: txMsgs.tx_chat, valid: true },
  tx_goal: { message: txMsgs.tx_goal, valid: true },
  tx_command: { message: txMsgs.tx_command, valid: true },
  tx_minimal: { message: { t: "tx", ch: "a", seq: 0, data: {} }, valid: true },
  tx_ch_max_len: {
    message: { t: "tx", ch: "c".repeat(TX_CH_MAX_LEN), seq: 1, data: {} },
    valid: true,
  },
  tx_data_at_cap: { message: { t: "tx", ch: "a", seq: 1, data: dataAtCap }, valid: true },
  tx_data_at_cap_utf8: {
    message: { t: "tx", ch: "a", seq: 1, data: { t: "é".repeat(446) } },
    valid: true,
  },
  tx_data_nested_null: {
    message: { t: "tx", ch: "a", seq: 1, data: { a: null, b: [1.5, null], c: { d: "é" } } },
    valid: true,
  },
  tx_seq_max_safe: {
    message: { t: "tx", ch: "a", seq: Number.MAX_SAFE_INTEGER, data: {} },
    valid: true,
  },
  tx_bad_data_oversize: {
    message: { t: "tx", ch: "a", seq: 1, data: { text: dataAtCap.text + "x" } },
    valid: false,
  },
  tx_bad_data_oversize_utf8: {
    message: { t: "tx", ch: "a", seq: 1, data: { t: "é".repeat(447) } },
    valid: false,
  },
  tx_bad_ch_too_long: {
    message: { t: "tx", ch: "c".repeat(TX_CH_MAX_LEN + 1), seq: 1, data: {} },
    valid: false,
  },
  tx_bad_ch_empty: { message: { t: "tx", ch: "", seq: 1, data: {} }, valid: false },
  tx_bad_ch_upper: { message: { t: "tx", ch: "Human_input", seq: 1, data: {} }, valid: false },
  tx_bad_ch_leading_digit: { message: { t: "tx", ch: "1ch", seq: 1, data: {} }, valid: false },
  tx_bad_ch_hyphen: { message: { t: "tx", ch: "human-input", seq: 1, data: {} }, valid: false },
  tx_bad_ch_reserved: { message: { t: "tx", ch: CONTROL_CHANNEL, seq: 1, data: {} }, valid: false },
  tx_bad_ch_type: { message: { t: "tx", ch: 5, seq: 1, data: {} }, valid: false },
  tx_bad_ch_missing: { message: { t: "tx", seq: 1, data: {} }, valid: false },
  tx_bad_seq_negative: { message: { t: "tx", ch: "a", seq: -1, data: {} }, valid: false },
  tx_bad_seq_fraction: { message: { t: "tx", ch: "a", seq: 1.5, data: {} }, valid: false },
  tx_bad_seq_string: { message: { t: "tx", ch: "a", seq: "1", data: {} }, valid: false },
  tx_bad_seq_bool: { message: { t: "tx", ch: "a", seq: true, data: {} }, valid: false },
  tx_bad_seq_beyond_safe: {
    message: { t: "tx", ch: "a", seq: Number.MAX_SAFE_INTEGER + 1, data: {} },
    valid: false,
  },
  tx_bad_seq_missing: { message: { t: "tx", ch: "a", data: {} }, valid: false },
  tx_bad_data_array: { message: { t: "tx", ch: "a", seq: 1, data: [] }, valid: false },
  tx_bad_data_null: { message: { t: "tx", ch: "a", seq: 1, data: null }, valid: false },
  tx_bad_data_string: { message: { t: "tx", ch: "a", seq: 1, data: "x" }, valid: false },
  tx_bad_data_missing: { message: { t: "tx", ch: "a", seq: 1 }, valid: false },
  // Extra keys are rejected on tx (elsewhere they are ignored): they would
  // carry bytes past the data cap. gen in particular: a tx is never stamped.
  tx_bad_extra_gen: { message: { ...txMsgs.tx_chat, gen: 3 }, valid: false },
  tx_bad_extra_key: { message: { ...txMsgs.tx_chat, later: 1.5 }, valid: false },
};

const dataFrames: Record<string, { header: FrameHeader; payload: Uint8Array }> = {
  odom_reliable: {
    header: { ch: "odom", seq: 42, ts: 1752576000.5, delivery: "reliable" },
    payload: new TextEncoder().encode('{"x":1.5,"y":-2.5,"yaw":0.75}'),
  },
  image_latest_meta: {
    header: {
      ch: "color_image",
      seq: 100,
      ts: 1752576001.25,
      delivery: "latest",
      meta: { w: 320, h: 240 },
    },
    payload: Uint8Array.from({ length: 256 }, (_, i) => i),
  },
  empty_payload: {
    header: { ch: "odom", seq: 0, ts: 0.5, delivery: "reliable" },
    payload: new Uint8Array(0),
  },
  // v5 robot hello: an @control frame whose payload is the datagram encoding
  // of the hello message (pins the payload-reuses-datagram-encoding rule).
  control_hello: {
    header: { ch: CONTROL_CHANNEL, seq: 1, ts: 1752576000.5, delivery: "reliable" },
    payload: encodeDatagram(controlMsgs.hello_robot),
  },
};

// Manifest vectors: valid cases pin normalization, invalid cases pin the
// rejection code. Inputs are declared here (invalid ones cannot come from an
// encoder); outputs come from parseManifest, and test_manifest.py pins the
// Python mirror against them. Most inputs leave dir/params/title absent to
// pin the defaulting; chImageFull pins explicit-field round-trips.
const chOdom = { ch: "odom", encoding: "pose.json.v1", delivery: "reliable", maxHz: 20.5 };
const chImage = { ch: "color_image", encoding: "jpeg.v1", delivery: "latest", maxHz: 15.5 };
const chImageFull = {
  ch: "color_image",
  dir: "rx",
  encoding: "jpeg.v1",
  delivery: "latest",
  maxHz: 15.5,
  params: { quality: 75.5 },
};
const chCostmap = {
  ch: "global_costmap",
  encoding: "costmap.zlib.v1",
  delivery: "latest",
  maxHz: 5.5,
};
const chTwist = {
  ch: "tele_cmd_vel",
  dir: "tx",
  encoding: "twist.json.v1",
  delivery: "latest",
  maxHz: 15.5,
  params: { maxLinear: 0.85, maxAngular: 1.5, boost: 2.5, watchdogMs: 300.5 },
};
const pCamera = { id: "camera", kind: "video", channels: ["color_image"] };
const pPose = { id: "pose", kind: "readout", channels: ["odom"] };
const longId = "x".repeat(65);
// Slot-table kinds (chat/navmap/control): the channels the microduck
// cockpit's bridge advertises, and the panels as dimos/web/cockpit.py emits
// them (role->channel mapping in params). Delivery is not part of the kind
// rules, so the values here are only representative.
const chChase = { ch: "chase_image", encoding: "jpeg.v1", delivery: "latest", maxHz: 12.5 };
const chAgent = { ch: "agent", encoding: "chat.json.v1", delivery: "reliable", maxHz: 30.5 };
const chAgentIdle = {
  ch: "agent_idle",
  encoding: "flag.json.v1",
  delivery: "reliable",
  maxHz: 10.5,
};
const chMode = { ch: "mode", encoding: "mode.json.v1", delivery: "reliable", maxHz: 10.5 };
const chHumanInput = {
  ch: "human_input",
  dir: "tx",
  encoding: "text.json.v1",
  delivery: "reliable",
  maxHz: 2.5,
};
const chPath = { ch: "path", encoding: "path.json.v1", delivery: "latest", maxHz: 5.5 };
const chPlaces = { ch: "places", encoding: "places.json.v1", delivery: "reliable", maxHz: 2.5 };
const chNavState = {
  ch: "nav_state",
  encoding: "navstate.json.v1",
  delivery: "latest",
  maxHz: 10.5,
};
const chGoal = {
  ch: "goal_request",
  dir: "tx",
  encoding: "pose_goal.json.v1",
  delivery: "reliable",
  maxHz: 5.5,
};
const chCommand = {
  ch: "ui_command",
  dir: "tx",
  encoding: "command.json.v1",
  delivery: "reliable",
  maxHz: 10.5,
};
const chPolicyState = {
  ch: "policy_state",
  encoding: "policy.json.v1",
  delivery: "latest",
  maxHz: 10.5,
};
const chatChannels = [chAgent, chAgentIdle, chMode, chHumanInput];
const pChat = {
  id: "chat",
  kind: "chat",
  title: "Agent",
  channels: ["agent", "agent_idle", "mode", "human_input"],
  params: { chat: "agent", idle: "agent_idle", mode: "mode", input: "human_input" },
};
const navmapChannels = [chCostmap, chOdom, chPath, chPlaces, chNavState, chGoal, chCommand];
const pNavMap = {
  id: "navmap",
  kind: "navmap",
  title: "Nav map",
  channels: ["global_costmap", "odom", "path", "places", "nav_state", "goal_request", "ui_command"],
  params: {
    costmap: "global_costmap",
    pose: "odom",
    path: "path",
    places: "places",
    navState: "nav_state",
    goal: "goal_request",
    command: "ui_command",
  },
};
const controlChannels = [chMode, chPolicyState, chNavState, chCommand];
const pControl = {
  id: "control",
  kind: "control",
  title: "Control",
  channels: ["mode", "policy_state", "nav_state", "ui_command"],
  params: { mode: "mode", policies: "policy_state", navState: "nav_state", command: "ui_command" },
};
const manifestCases: Record<string, unknown> = {
  channels_only: { version: 1, channels: [chImage, chOdom] },
  empty: { version: 1, channels: [] },
  full: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [
      { ...pCamera, title: "Cameră față" },
      pPose,
      { id: "drive", kind: "joystick", channels: [] },
      { id: "aux", kind: "readout", channels: ["odom"] },
    ],
    layout: { row: [{ col: ["camera", "pose"], shares: [2.5, 1.5] }, "drive"] },
    pages: ["aux"],
  },
  extra_keys_ignored: {
    version: 1,
    channels: [{ ...chOdom, later: 1.5 }],
    panels: [{ ...pPose, future: true }],
    layout: { row: ["pose"], future: true },
    unknown_top_level: { x: 1 },
  },
  not_an_object: [1, 2],
  version_missing: { channels: [] },
  version_string: { version: "1", channels: [] },
  version_bool: { version: true, channels: [] },
  version_two: { version: 2, channels: [] },
  version_float: { version: 1.5, channels: [] },
  // The version gate runs before the channel shape check, so a future
  // manifest whose channels no longer parse still reports its version.
  version_before_channel_shape: { version: 2, channels: { alien: true } },
  missing_channels: { version: 1 },
  channel_bad_shape: { version: 1, channels: [{ ch: "odom" }] },
  bad_delivery: { version: 1, channels: [{ ...chOdom, delivery: "sometimes" }] },
  max_hz_string: { version: 1, channels: [{ ...chOdom, maxHz: "20" }] },
  max_hz_bool: { version: 1, channels: [{ ...chOdom, maxHz: true }] },
  empty_channel_id: { version: 1, channels: [{ ...chOdom, ch: "" }] },
  long_channel_id: { version: 1, channels: [{ ...chOdom, ch: longId }] },
  reserved_channel_id: { version: 1, channels: [{ ...chOdom, ch: CONTROL_CHANNEL }] },
  duplicate_channel_id: { version: 1, channels: [chOdom, { ...chOdom, encoding: "jpeg.v1" }] },
  empty_encoding: { version: 1, channels: [{ ...chOdom, encoding: "" }] },
  long_encoding: { version: 1, channels: [{ ...chOdom, encoding: longId }] },
  zero_max_hz: { version: 1, channels: [{ ...chOdom, maxHz: 0 }] },
  negative_max_hz: { version: 1, channels: [{ ...chOdom, maxHz: -2.5 }] },
  dir_tx_channel: { version: 1, channels: [{ ...chOdom, dir: "tx" }] },
  dir_invalid: { version: 1, channels: [{ ...chOdom, dir: "both" }] },
  dir_null: { version: 1, channels: [{ ...chOdom, dir: null }] },
  channel_params_roundtrip: { version: 1, channels: [chImageFull] },
  channel_params_not_object: { version: 1, channels: [{ ...chOdom, params: 1.5 }] },
  panels_not_list: { version: 1, channels: [chOdom], panels: {} },
  null_panels: { version: 1, channels: [chOdom], panels: null },
  panel_bad_shape: { version: 1, channels: [chOdom], panels: [{ id: "a" }] },
  panel_channels_not_strings: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "a", kind: "readout", channels: [1.5] }],
  },
  panel_title_roundtrip: {
    version: 1,
    channels: [chOdom],
    panels: [{ ...pPose, title: "Poziție" }],
  },
  panel_title_not_string: { version: 1, channels: [chOdom], panels: [{ ...pPose, title: 1.5 }] },
  panel_params_not_object: { version: 1, channels: [chOdom], panels: [{ ...pPose, params: [] }] },
  empty_panel_id: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "", kind: "readout", channels: [] }],
  },
  empty_panel_kind: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "a", kind: "", channels: [] }],
  },
  duplicate_panel_id: {
    version: 1,
    channels: [chOdom],
    panels: [
      { id: "a", kind: "readout", channels: [] },
      { id: "a", kind: "video", channels: [] },
    ],
  },
  panel_unknown_channel: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "a", kind: "video", channels: ["lidar"] }],
  },
  video_panel_no_channel: {
    version: 1,
    channels: [chImage],
    panels: [{ id: "cam", kind: "video", channels: [] }],
  },
  video_panel_two_channels: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [{ id: "cam", kind: "video", channels: ["color_image", "odom"] }],
  },
  video_panel_wrong_encoding: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "cam", kind: "video", channels: ["odom"] }],
  },
  video_panel_wrong_delivery: {
    version: 1,
    channels: [{ ...chImage, delivery: "reliable" }],
    panels: [{ id: "cam", kind: "video", channels: ["color_image"] }],
  },
  video_panel_tx_channel: {
    version: 1,
    channels: [{ ...chImage, dir: "tx" }],
    panels: [{ id: "cam", kind: "video", channels: ["color_image"] }],
  },
  map2d_panel_full: {
    version: 1,
    channels: [chCostmap, chOdom],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap", "odom"] }],
  },
  map2d_panel_no_pose: {
    version: 1,
    channels: [chCostmap],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap"] }],
  },
  map2d_panel_no_channel: {
    version: 1,
    channels: [chCostmap],
    panels: [{ id: "map", kind: "map2d", channels: [] }],
  },
  map2d_panel_three_channels: {
    version: 1,
    channels: [chCostmap, chOdom, chImage],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap", "odom", "color_image"] }],
  },
  map2d_panel_wrong_encoding: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "map", kind: "map2d", channels: ["odom"] }],
  },
  map2d_panel_wrong_delivery: {
    version: 1,
    channels: [{ ...chCostmap, delivery: "reliable" }],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap"] }],
  },
  map2d_panel_bad_pose: {
    version: 1,
    channels: [chCostmap, chImage],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap", "color_image"] }],
  },
  map2d_panel_tx_costmap: {
    version: 1,
    channels: [{ ...chCostmap, dir: "tx" }],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap"] }],
  },
  map2d_panel_tx_pose: {
    version: 1,
    channels: [chCostmap, { ...chOdom, dir: "tx" }],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap", "odom"] }],
  },
  teleop_panel_valid: {
    version: 1,
    channels: [chTwist],
    panels: [{ id: "drive", kind: "teleop", channels: ["tele_cmd_vel"] }],
  },
  teleop_panel_no_channel: {
    version: 1,
    channels: [chTwist],
    panels: [{ id: "drive", kind: "teleop", channels: [] }],
  },
  teleop_panel_two_channels: {
    version: 1,
    channels: [chTwist, chOdom],
    panels: [{ id: "drive", kind: "teleop", channels: ["tele_cmd_vel", "odom"] }],
  },
  teleop_panel_rx_channel: {
    version: 1,
    channels: [{ ...chTwist, dir: "rx" }],
    panels: [{ id: "drive", kind: "teleop", channels: ["tele_cmd_vel"] }],
  },
  teleop_panel_wrong_encoding: {
    version: 1,
    channels: [{ ...chOdom, dir: "tx" }],
    panels: [{ id: "drive", kind: "teleop", channels: ["odom"] }],
  },
  teleop_panel_wrong_delivery: {
    version: 1,
    channels: [{ ...chTwist, delivery: "reliable" }],
    panels: [{ id: "drive", kind: "teleop", channels: ["tele_cmd_vel"] }],
  },
  // chat: [chat.json.v1 rx, flag.json.v1 rx, mode.json.v1 rx, text.json.v1 tx]
  chat_panel_valid: { version: 1, channels: chatChannels, panels: [pChat] },
  chat_panel_three_channels: {
    version: 1,
    channels: chatChannels,
    panels: [{ ...pChat, channels: ["agent", "agent_idle", "mode"] }],
  },
  chat_panel_five_channels: {
    version: 1,
    channels: [...chatChannels, chOdom],
    panels: [{ ...pChat, channels: [...pChat.channels, "odom"] }],
  },
  chat_panel_wrong_encoding: {
    version: 1,
    channels: [...chatChannels, chOdom],
    panels: [{ ...pChat, channels: ["odom", "agent_idle", "mode", "human_input"] }],
  },
  chat_panel_slots_swapped: {
    version: 1,
    channels: chatChannels,
    panels: [{ ...pChat, channels: ["agent", "mode", "agent_idle", "human_input"] }],
  },
  chat_panel_input_rx: {
    version: 1,
    channels: [chAgent, chAgentIdle, chMode, { ...chHumanInput, dir: "rx" }],
    panels: [pChat],
  },
  chat_panel_chat_tx: {
    version: 1,
    channels: [{ ...chAgent, dir: "tx" }, chAgentIdle, chMode, chHumanInput],
    panels: [pChat],
  },
  // Slot rules pin encoding + dir only; delivery is the bridge's choice.
  chat_panel_any_delivery: {
    version: 1,
    channels: [chAgent, chAgentIdle, chMode, { ...chHumanInput, delivery: "latest" }],
    panels: [pChat],
  },
  // An undeclared channel is reported before the kind rule runs.
  chat_panel_unknown_channel_first: {
    version: 1,
    channels: [chAgent, chAgentIdle, chMode],
    panels: [pChat],
  },
  // navmap: [costmap.zlib.v1 rx, pose.json.v1 rx, path.json.v1 rx,
  //          places.json.v1 rx, navstate.json.v1 rx, pose_goal.json.v1 tx,
  //          command.json.v1 tx]
  navmap_panel_valid: { version: 1, channels: navmapChannels, panels: [pNavMap] },
  navmap_panel_six_channels: {
    version: 1,
    channels: navmapChannels,
    panels: [{ ...pNavMap, channels: pNavMap.channels.slice(0, 6) }],
  },
  navmap_panel_wrong_costmap: {
    version: 1,
    channels: navmapChannels,
    panels: [{ ...pNavMap, channels: ["odom", ...pNavMap.channels.slice(1)] }],
  },
  navmap_panel_goal_rx: {
    version: 1,
    channels: [
      chCostmap,
      chOdom,
      chPath,
      chPlaces,
      chNavState,
      { ...chGoal, dir: "rx" },
      chCommand,
    ],
    panels: [pNavMap],
  },
  navmap_panel_path_tx: {
    version: 1,
    channels: [
      chCostmap,
      chOdom,
      { ...chPath, dir: "tx" },
      chPlaces,
      chNavState,
      chGoal,
      chCommand,
    ],
    panels: [pNavMap],
  },
  navmap_panel_outputs_swapped: {
    version: 1,
    channels: navmapChannels,
    panels: [{
      ...pNavMap,
      channels: [...pNavMap.channels.slice(0, 5), "ui_command", "goal_request"],
    }],
  },
  // control: [mode.json.v1 rx, policy.json.v1 rx, navstate.json.v1 rx, command.json.v1 tx]
  control_panel_valid: { version: 1, channels: controlChannels, panels: [pControl] },
  control_panel_no_channel: {
    version: 1,
    channels: controlChannels,
    panels: [{ ...pControl, channels: [] }],
  },
  control_panel_wrong_policy: {
    version: 1,
    channels: controlChannels,
    panels: [{ ...pControl, channels: ["mode", "nav_state", "nav_state", "ui_command"] }],
  },
  control_panel_command_rx: {
    version: 1,
    channels: [chMode, chPolicyState, chNavState, { ...chCommand, dir: "rx" }],
    panels: [pControl],
  },
  control_panel_mode_tx: {
    version: 1,
    channels: [{ ...chMode, dir: "tx" }, chPolicyState, chNavState, chCommand],
    panels: [pControl],
  },
  // The whole microduck cockpit (MICRODUCK_COCKPIT_LAYOUT): shared channels
  // (mode, nav_state, ui_command, odom) declared once, bound by several panels.
  cockpit_microduck: {
    version: 1,
    channels: [
      chMode,
      chPolicyState,
      chNavState,
      chCommand,
      chChase,
      chCostmap,
      chOdom,
      chPath,
      chPlaces,
      chGoal,
      chImage,
      chTwist,
      chAgent,
      chAgentIdle,
      chHumanInput,
    ],
    panels: [
      { ...pControl, id: "p0" },
      { id: "p1", kind: "video", title: "Chase cam", channels: ["chase_image"] },
      { ...pNavMap, id: "p2" },
      { id: "p3", kind: "video", title: "Head cam", channels: ["color_image"] },
      { id: "p4", kind: "teleop", channels: ["tele_cmd_vel"] },
      { ...pChat, id: "p5" },
    ],
    layout: {
      col: [
        "p0",
        {
          row: [
            "p1",
            { col: ["p2", { row: ["p3", "p4"], shares: [1.5, 1.5] }], shares: [3.5, 2.5] },
            "p5",
          ],
          shares: [5.5, 4.5, 3.5],
        },
      ],
      shares: [1.5, 11.5],
    },
  },
  layout_single_panel: { version: 1, channels: [chOdom], panels: [pPose], layout: "pose" },
  layout_row_shares: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose],
    layout: { row: ["camera", "pose"], shares: [2.5, 1.5] },
  },
  // Outer col has no shares: pins that absent shares stay absent in the
  // normalized tree (the equal-split default belongs to the renderer).
  layout_nested_tree: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose, { id: "drive", kind: "joystick", channels: [] }],
    layout: { col: [{ row: ["camera", "pose"], shares: [1.5, 2.5] }, "drive"] },
  },
  layout_null: { version: 1, channels: [chOdom], panels: [pPose], layout: null },
  layout_bad_node_type: { version: 1, channels: [chOdom], panels: [pPose], layout: 1.5 },
  layout_flat_list_rejected: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: ["pose"],
  },
  layout_row_and_col: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose],
    layout: { row: ["camera"], col: ["pose"] },
  },
  layout_neither_row_nor_col: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { shares: [1.5] },
  },
  layout_children_not_array: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: "pose" },
  },
  layout_empty_children: { version: 1, channels: [chOdom], panels: [pPose], layout: { row: [] } },
  layout_nested_bad_node: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: [{ col: [2.5] }] },
  },
  layout_shares_not_array: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: "big" },
  },
  layout_shares_not_numbers: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: ["2"] },
  },
  layout_shares_bool: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: [true] },
  },
  layout_shares_length_mismatch: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose],
    layout: { row: ["camera", "pose"], shares: [1.5] },
  },
  layout_share_zero: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: [0] },
  },
  layout_share_negative: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: [-1.5] },
  },
  layout_share_null: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: [null] },
  },
  layout_unknown_panel: { version: 1, channels: [chOdom], panels: [pPose], layout: "ghost" },
  layout_deep_unknown_panel: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: [{ col: ["ghost"] }] },
  },
  duplicate_layout_panel: {
    version: 1,
    channels: [chImage],
    panels: [pCamera],
    layout: { row: ["camera", "camera"] },
  },
  duplicate_panel_across_layout_and_pages: {
    version: 1,
    channels: [chImage],
    panels: [pCamera],
    layout: "camera",
    pages: ["camera"],
  },
  duplicate_panel_within_pages: {
    version: 1,
    channels: [chImage],
    panels: [pCamera],
    pages: ["camera", "camera"],
  },
  pages_only: { version: 1, channels: [chOdom], panels: [pPose], pages: ["pose"] },
  pages_and_layout: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose],
    layout: "camera",
    pages: ["pose"],
  },
  unknown_page_panel: { version: 1, channels: [chOdom], panels: [pPose], pages: ["ghost"] },
  // Layout is validated before pages: the layout's unknown panel wins.
  layout_error_before_pages: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: "ghost",
    pages: ["phantom"],
  },
  pages_not_list: { version: 1, channels: [chOdom], panels: [pPose], pages: {} },
  pages_not_strings: { version: 1, channels: [chOdom], panels: [pPose], pages: [1.5] },
  pages_null: { version: 1, channels: [chOdom], panels: [pPose], pages: null },
};

const control = {
  vectors: Object.entries(controlMsgs).map(([name, message]) => ({
    name,
    message,
    b64: b64(encodeControlFrame(message)),
  })),
};

const datagrams = {
  vectors: Object.entries({ ...controlMsgs, ...teleopMsgs }).map(([name, message]) => ({
    name,
    message,
    b64: b64(encodeDatagram(message)),
  })),
};

const data = {
  vectors: Object.entries(dataFrames).map(([name, { header, payload }]) => ({
    name,
    header,
    payload_b64: b64(payload),
    frame_b64: b64(encodeDataFrame(header, payload)),
  })),
};

const manifests = {
  vectors: Object.entries(manifestCases).map(([name, data]) => {
    try {
      return { name, data, manifest: parseManifest(data) };
    } catch (e) {
      if (e instanceof ManifestError) return { name, data, error: e.code };
      throw e;
    }
  }),
};

// Generic tx commands: `valid` pins whether msgFromUnknown accepts the
// message; valid vectors also carry the byte-exact datagram encoding.
const txMessages = {
  vectors: Object.entries(txCases).map(([name, { message, valid }]) => {
    const parsed = msgFromUnknown(message);
    if ((parsed !== null) !== valid) {
      throw new Error(`tx fixture ${name}: expected valid=${valid}, got ${parsed !== null}`);
    }
    return valid
      ? { name, message, valid, b64: b64(encodeDatagram(parsed as TxMsg)) }
      : { name, message, valid };
  }),
};

const dir = new URL(".", import.meta.url);
for (
  const [file, obj] of [
    ["control_frames.json", control],
    ["datagrams.json", datagrams],
    ["data_frames.json", data],
    ["manifests.json", manifests],
    ["tx_messages.json", txMessages],
  ] as const
) {
  await Deno.writeTextFile(new URL(file, dir), JSON.stringify(obj, null, 2) + "\n");
  console.log(`wrote ${file}`);
}
