// Copyright 2026 Dimensional Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use anyhow::{bail, Context, Result};
use std::path::Path;
use std::process::Command;
use std::time::{Duration, Instant};

pub fn checked(command: &mut Command) -> Result<()> {
    let status = command
        .status()
        .with_context(|| format!("starting {command:?}"))?;
    if !status.success() {
        bail!("{command:?} failed with {status}");
    }
    Ok(())
}

pub fn checked_timeout(command: &mut Command, timeout: Duration) -> Result<()> {
    let mut child = command
        .spawn()
        .with_context(|| format!("starting {command:?}"))?;
    let start = Instant::now();
    loop {
        if let Some(status) = child.try_wait()? {
            if !status.success() {
                bail!("{command:?} failed with {status}");
            }
            return Ok(());
        }
        if start.elapsed() >= timeout {
            child.kill()?;
            child.wait()?;
            bail!(
                "Dependency check timed out after {} seconds: {command:?}",
                timeout.as_secs()
            );
        }
        std::thread::sleep(Duration::from_millis(50));
    }
}

pub fn activation(project: &Path, pixi: &Path) -> String {
    let root = esc(&project.to_string_lossy());
    let pixi = esc(&pixi.to_string_lossy());
    format!(
        r#"# Generated by dim setup. Source in Bash or Zsh; do not execute.
# A venv's deactivate restores PATH; do that before Pixi changes PATH.
if typeset -f deactivate >/dev/null 2>&1; then deactivate; fi
_dim_project={root}
_dim_shell=bash
if [ -n "${{ZSH_VERSION:-}}" ]; then _dim_shell=zsh; fi
_dim_hook=$({pixi} shell-hook --shell "$_dim_shell" --as-is --manifest-path "$_dim_project/.dimos/pixi.toml") || return
eval "$_dim_hook" || return
unset _dim_hook _dim_shell
source "$_dim_project/.venv/bin/activate" || return
# Wheel-loaded shared libraries need the Pixi library directory too.
export LD_LIBRARY_PATH="$CONDA_PREFIX/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
export PKG_CONFIG_PATH="$CONDA_PREFIX/lib/pkgconfig${{PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}}"
# PyAudio hardcodes -I/usr/include. Keep host headers after the compiler's
# sysroot even when a package explicitly adds these directories with -I.
export CPPFLAGS="${{CPPFLAGS:+$CPPFLAGS }}-idirafter /usr/local/include -idirafter /usr/include"
unset _dim_project
"#
    )
}

pub fn command(project: &Path, args: &[String]) -> Command {
    let mut command = Command::new("bash");
    command
        .arg("--noprofile")
        .arg("--norc")
        .arg("-c")
        .arg("source \"$1\" || exit; shift; exec \"$@\"")
        .arg("dim-run")
        .arg(project.join(".dimos/activate.sh"))
        .args(args)
        .current_dir(project);
    command
}

pub fn esc(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}
