name: build-devcontainer
permissions:
  contents: read
  packages: write

on:
  push:
    paths:
      - "flake.*"
      - ".github/workflows/build-devcontainer.yml"

jobs:
  build:
    runs-on: dimos-runner-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull docker layer cache
        run: docker pull ghcr.io/dimensionalos/dimos-dev:latest || true

      - run: nix build .#devcontainer

      - name: Docker push
      - run: |
          docker load < result
          docker tag dimensionalos/dimos-dev:latest ghcr.io/dimensionalos/dimos-dev:latest
          docker push ghcr.io/dimensionalos/dimos-dev:latest
