name: ci
on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  packages: read

jobs:
  ci-complete:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on: [self-hosted, Linux]
    container:
      image: ghcr.io/dimensionalos/ros-dev:dev
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        ALIBABA_API_KEY: ${{ secrets.ALIBABA_API_KEY }}

    steps:
      - uses: actions/checkout@v5
        with:
          clean: false

      - name: Fix permissions
        run: |
          git config --global --add safe.directory '*'
          git clean -ffdx -e .venv

      - name: Verify
        run: bash ./scripts/verify.sh

      - name: Check disk space
        if: failure()
        run: |
          df -h
