name: docker-tree
on:
  pull_request:
    branches:
      - dev
      - main
      - master
#  push:
#    branches: [ env/devcontainer2 ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_TAG: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}


jobs:
  check-changes:
    runs-on: dimos-runner-ubuntu-2204
    outputs:
      ros:    ${{ steps.filter.outputs.ros }}
      python: ${{ steps.filter.outputs.python }}
      dev:    ${{ steps.filter.outputs.dev }}
      tests:  ${{ steps.filter.outputs.tests }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.event.before }}
          filters: |
            ros:
              # ros rebuild will cascade to full rebuild
              # this is why check-changes to this workflow trigger ros
              - .github/workflows/_docker-build-template.yml
              - .github/workflows/docker.yml
              - docker/base-ros/**

            python:
              - docker/base-python/**
              - requirements*.txt

            dev:
              - docker/dev/**

            tests:
              - dimos/**

  # this needs a fix, for now it's always "latest"
  set-tag:
    runs-on: dimos-runner-ubuntu-2204
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - name: Determine Image Tag
        id: set-tag
        run: |
          if [ "${GITHUB_REF_NAME}" == "master" ]; then
            echo "image_tag=latest" >> $GITHUB_ENV
          else
            echo "image_tag=latest" >> $GITHUB_ENV
          fi

  debug-vars:
    runs-on: dimos-runner-ubuntu-2204
    needs: [set-tag, check-changes]     # keep the links so we can read their data
    # The extra test on result makes the job “eligible” even if build-dev was skipped
    steps:
      - name: Show the values the test job uses
        env:
          TESTS_FLAG:       ${{ needs.check-changes.outputs.tests }}
          TAG:       ${{ needs.set-tag.outputs.image-tag }}
          BUILD_DEV_RESULT: ${{ needs.build-dev.result }}
        run: |
          echo "needs.check-changes.outputs.tests    = '${TESTS_FLAG}'"
          echo "needs.build-dev.result         = '${BUILD_DEV_RESULT}'"
          echo "docker tag         = '${TAG}'"

  build-ros:
    needs: [check-changes, set-tag]
    if: needs.check-changes.outputs.ros == 'true'
    uses: ./.github/workflows/_docker-build-template.yml
    with:
      image-tag:   ghcr.io/dimensionalos/base-ros:${{ needs.set-tag.outputs.image-tag }}
      dockerfile:  docker/base-ros/Dockerfile
      cache-scope: base-ros

  build-python:
    needs: [check-changes, set-tag, build-ros]
    if: |
      ${{
      always() && !cancelled() &&
      needs.check-changes.result == 'success' &&
      ((needs.build-ros.result == 'success') ||
      (needs.build-ros.result == 'skipped' &&
      needs.check-changes.outputs.python == 'true'))
      }}

    run: |
      echo '=== needs context ==='
      echo '${{ toJSON(needs) }}'

    uses: ./.github/workflows/_docker-build-template.yml
    with:
      image-tag:   ghcr.io/dimensionalos/base-ros-python:${{ needs.set-tag.outputs.image-tag }}
      dockerfile:  docker/base-ros-python/Dockerfile
      cache-scope: base-python

  build-dev:
    needs: [check-changes, set-tag, build-python]
    if: |
      ${{
      always() && !cancelled() &&
      needs.check-changes.result == 'success' &&
      ((needs.build-python.result == 'success') ||
      (needs.build-python.result == 'skipped' &&
      needs.check-changes.outputs.dev == 'true'))
      }}

    uses: ./.github/workflows/_docker-build-template.yml
    with:
      image-tag:   ghcr.io/dimensionalos/dev:${{ needs.set-tag.outputs.image-tag }}
      dockerfile:  docker/dev/Dockerfile
      cache-scope: dev

  run-tests:
    needs: [check-changes, build-dev]
    if: |
      ${{
      always() && !cancelled() &&
      needs.check-changes.result == 'success' &&
      ((needs.build-dev.result == 'success') ||
      (needs.build-dev.result == 'skipped' &&
      needs.check-changes.outputs.tests == 'true'))
      }}
    uses: ./.github/workflows/pytest.yml
