name: build-base-ros
permissions:
  contents: read
  packages: write

concurrency:
  group: docker-base-ros
  cancel-in-progress: true

on:
  push:
    paths:
      - ".github/workflows/docker-base-ros.yml"
      - "docker/base-ros/**"
jobs:
  build:
    runs-on: dimos-runner-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: docker/base-ros/Dockerfile
          tags: ghcr.io/dimensionalos/base-ros:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

