name: docker-tree
on:
  push:
    branches: [ env/devcontainer2 ]

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: dimos-runner-ubuntu-2204
    outputs:
      ros:    ${{ steps.filter.outputs.ros }}
      python: ${{ steps.filter.outputs.python }}
      dev:    ${{ steps.filter.outputs.dev }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.event.before }}
          filters: |
            all:
              - .github/workflows/_docker-build-template.yml
              - .github/workflows/docker.yml

            ros: &all
              - docker/base-ros/**

            python: &all
              - docker/base-python/**
              - requirements*.txt

            dev: &all
              - docker/dev/**

            tests:
              - dimos/**

  build-ros:
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.ros == 'true'
    uses: ./.github/workflows/_docker-build-template.yml
    with:
      image-tag:   ghcr.io/dimensionalos/base-ros:latest
      dockerfile:  docker/base-ros/Dockerfile
      cache-scope: base-ros

  build-python:
    needs: [detect-changes, build-ros]
    if: ${{ needs.detect-changes.outputs.python == 'true' &&
            (needs.build-ros.result == 'success' ||
             needs.build-ros.result == 'skipped') }}

    uses: ./.github/workflows/_docker-build-template.yml
    with:
      image-tag:   ghcr.io/dimensionalos/base-ros-python:latest
      dockerfile:  docker/base-ros-python/Dockerfile
      cache-scope: base-python

  build-dev:
    needs: [detect-changes, build-python]
    if: ${{ needs.detect-changes.outputs.dev == 'true' &&
            (needs.build-python.result == 'success' ||
             needs.build-python.result == 'skipped') }}
    uses: ./.github/workflows/_docker-build-template.yml
    with:
      image-tag:   ghcr.io/dimensionalos/dev:latest
      dockerfile:  docker/dev/Dockerfile
      cache-scope: dev

  run-tests:
    runs-on: dimos-runner-ubuntu-2204
    needs: [detect-changes, build-dev]
    if: ${{ always() && needs.detect-changes.outputs.tests == 'true' &&
            (needs.build-dev.result == 'success' ||
             needs.build-dev.result == 'skipped') }}
    container:
      image: ghcr.io/dimensionalos/dev:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: pytest-3 -sv dimos/
