name: PR Tests

on:
  pull_request:

permissions:
  contents: write
  packages: write
  pull-requests: read
  workflows: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run PR test script
        run: bash scripts/test_pr.sh

