name: docker-tree
on:
  push:
    branches: [ env/devcontainer2 ]

permissions:
  contents: read
  packages: write

jobs:
  run-tests:
    runs-on: dimos-runner-ubuntu-2204

    container:
      image: ghcr.io/dimensionalos/dev:latest

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          /entrypoint.sh bash -c "pytest-3 -sv dimos/"
